; This file for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_the_trial_of_kharzoid_ost=music_data_the_trial_of_kharzoid_ost
.endif

music_data_the_trial_of_kharzoid_ost:
	.byte 6
	.word @instruments
	.word @samples-148
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4
	.byte .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid), 0, 0
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4
	.byte .lobyte(@tempo_env_8_mid), .hibyte(@tempo_env_8_mid), 0, 0
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4
	.byte .lobyte(@tempo_env_18_mid), .hibyte(@tempo_env_18_mid), 0, 0
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4
	.byte .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid), 0, 0
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4
	.byte .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid), 0, 0
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4
	.byte .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid), 0, 0

.export music_data_the_trial_of_kharzoid_ost
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env15,@env0,@env11,@env8
	.word @env14,@env0,@env12,@env8
	.word @env7,@env0,@env10,@env8
	.word @env13,@env0,@env16,@env8
	.word @env3,@env0,@env12,@env8
	.word @env5,@env0,@env11,@env8
	.word @env6,@env0,@env10,@env8
	.word @env1,@env0,@env12,@env4
	.word @env9,@env0,@env12,@env2

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$9c,$0f,$40	;37 (sample_tom)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;38 
	.byte $27+.lobyte(FAMISTUDIO_DPCM_PTR),$9c,$0f,$40	;39 (sfx_voice_D)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;40 
	.byte $4e+.lobyte(FAMISTUDIO_DPCM_PTR),$9c,$0f,$40	;41 (sfx_voice_Em)

@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $00,$c1,$02,$c2,$c2,$c3,$c4,$00,$06
@env2:
	.byte $00,$c0,$0d,$c1,$c1,$c0,$03,$bf,$bf,$c0,$03,$c1,$c1,$c0,$03,$c1,$05,$c0,$03,$bf,$04,$bf,$00,$0f
@env3:
	.byte $00,$c1,$c3,$03,$c4,$02,$c3,$02,$c2,$c2,$c1,$00,$0a
@env4:
	.byte $00,$c0,$07,$c1,$c1,$c0,$03,$bf,$bf,$c0,$03,$c1,$03,$c0,$03,$bf,$02,$bf,$00,$09
@env5:
	.byte $04,$c5,$7f,$00,$01
@env6:
	.byte $00,$c0,$c0,$c1,$0b,$c2,$02,$c3,$04,$c4,$04,$c5,$03,$c6,$c6,$c7,$02,$c8,$c9,$ca,$cb,$cb,$cc,$ce,$ce,$cf,$c7,$c7,$c6,$03,$c5,$c5,$c4,$c4,$c3,$03,$c2,$c2,$c1,$c1,$c0,$00,$28
@env7:
	.byte $00,$cf,$c4,$c5,$c6,$c7,$c8,$ca,$cb,$c4,$c3,$c4,$c4,$c5,$c6,$c8,$c9,$c2,$c1,$c2,$c3,$c4,$c5,$c6,$c7,$c0,$c0,$c1,$c2,$c3,$c4,$c5,$c0,$00,$20
@env8:
	.byte $00,$c0,$7f,$00,$01
@env9:
	.byte $14,$c3,$c4,$05,$c5,$06,$c6,$03,$c7,$02,$c8,$04,$c9,$02,$c8,$c8,$c7,$02,$00,$10,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$c2,$c1,$c1,$c0,$00,$20
@env10:
	.byte $7f,$00,$00
@env11:
	.byte $c2,$7f,$00,$00
@env12:
	.byte $c1,$7f,$00,$00
@env13:
	.byte $00,$c8,$ce,$cc,$ca,$c9,$c9,$c8,$c8,$c7,$02,$c6,$c6,$c5,$c4,$c3,$02,$c2,$c2,$c1,$02,$c0,$00,$15
@env14:
	.byte $00,$c6,$c9,$c6,$c4,$c4,$c3,$c2,$c1,$00,$08
@env15:
	.byte $04,$c7,$7f,$00,$01
@env16:
	.byte $c0,$02,$c1,$02,$c0,$00,$04
@tempo_env_10_mid:
	.byte $03,$04,$06,$05,$05,$05,$80
@tempo_env_8_mid:
	.byte $03,$05,$04,$06,$05,$80
@tempo_env_18_mid:
	.byte $03,$05,$05,$05,$80
@song0ch0:
@song0ch0loop:
	.byte $6a, .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid)
@song0ref5:
	.byte $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b
	.byte $ff, $0b
	.word @song0ref5
	.byte $8e, $35, $cd, $6b, $00, $81, $3a, $f7, $f1, $38, $cd, $6b, $3a, $f7, $f5, $3c, $cd, $6b, $38, $f7, $f5, $36, $cd, $6b
	.byte $38, $f7, $f5, $35, $cd, $6b, $3a, $f7, $f5, $3c, $cd, $6b, $3d, $f7, $f5, $41, $cd, $6b, $3f, $cd, $62, $38, $f7, $a5
	.byte $3a, $cd, $6b, $3c, $f7, $f5, $41, $cd, $6b, $00, $f7, $f7, $cd, $6b, $46, $f7, $f7, $cd, $6b, $46, $f7, $f7, $cd, $6b
	.byte $46, $f7, $f7, $cd, $6b, $88
@song0ref102:
	.byte $3f
@song0ref103:
	.byte $87, $40, $87, $41, $87, $42, $87, $43, $87, $44, $87, $46, $87, $44, $87, $43, $87, $42, $87, $41
	.byte $ff, $14
	.word @song0ref103
	.byte $ff, $14
	.word @song0ref103
	.byte $87, $40, $87, $6b
	.byte $ff, $15
	.word @song0ref102
	.byte $ff, $14
	.word @song0ref103
	.byte $ff, $14
	.word @song0ref103
	.byte $87, $40, $87, $6b
	.byte $ff, $15
	.word @song0ref102
	.byte $ff, $14
	.word @song0ref103
	.byte $ff, $14
	.word @song0ref103
	.byte $87, $40, $87, $6b
	.byte $ff, $15
	.word @song0ref102
	.byte $ff, $14
	.word @song0ref103
	.byte $ff, $14
	.word @song0ref103
	.byte $87, $40, $87, $6b, $00, $f7, $f7, $cd, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $90
@song0ref205:
	.byte $1b, $f7, $f3, $00, $81, $1d, $cb, $1e, $f7, $f7, $20, $c9, $00, $85, $1d, $f7, $f1, $1b, $c9, $00, $1d, $f7, $f5, $19
	.byte $cd
	.byte $ff, $19
	.word @song0ref205
	.byte $ff, $19
	.word @song0ref205
	.byte $8e
@song0ref237:
	.byte $46, $f7, $f7, $c9, $00, $81, $45, $f7, $f7, $cd, $44, $f7, $f7, $cd, $43, $f7, $f7, $cd
	.byte $ff, $12
	.word @song0ref237
	.byte $00, $f7, $f7, $cd, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80
@song0ref276:
	.byte $1b, $81, $1b, $a1, $1e, $81, $1b, $a1, $22, $81, $1b, $a1, $27, $81, $1b, $a1, $2e, $81, $1b, $f7, $a1
	.byte $ff, $15
	.word @song0ref276
@song0ref300:
	.byte $1d, $81, $1d, $a1, $20, $81, $1d, $a1, $24, $81, $1d, $9f, $00, $29, $81, $1d, $a1, $2c, $81, $1d, $f7, $a1
	.byte $ff, $16
	.word @song0ref300
	.byte $ff, $15
	.word @song0ref276
	.byte $ff, $15
	.word @song0ref276
	.byte $ff, $16
	.word @song0ref300
	.byte $ff, $16
	.word @song0ref300
	.byte $ff, $15
	.word @song0ref276
	.byte $ff, $15
	.word @song0ref276
	.byte $ff, $16
	.word @song0ref300
	.byte $ff, $16
	.word @song0ref300
	.byte $ff, $15
	.word @song0ref276
	.byte $ff, $15
	.word @song0ref276
	.byte $ff, $16
	.word @song0ref300
	.byte $ff, $16
	.word @song0ref300
	.byte $ff, $15
	.word @song0ref276
	.byte $ff, $15
	.word @song0ref276
	.byte $ff, $15
	.word @song0ref276
	.byte $ff, $15
	.word @song0ref276
	.byte $ff, $15
	.word @song0ref276
	.byte $ff, $15
	.word @song0ref276
	.byte $ff, $15
	.word @song0ref276
	.byte $ff, $15
	.word @song0ref276
	.byte $ff, $15
	.word @song0ref276
	.byte $ff, $15
	.word @song0ref276
	.byte $ff, $15
	.word @song0ref276
	.byte $ff, $15
	.word @song0ref276
	.byte $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref401:
	.byte $86, $2f, $cd, $2e, $cd, $2f, $cd, $2e, $83, $8c, $2e, $c7, $86, $2f, $cd, $2e, $cd, $2f, $cd, $2e, $83, $8c, $2e, $c7
	.byte $ff, $14
	.word @song0ref401
	.byte $ff, $14
	.word @song0ref401
	.byte $ff, $14
	.word @song0ref401
	.byte $ff, $14
	.word @song0ref401
	.byte $ff, $14
	.word @song0ref401
	.byte $ff, $14
	.word @song0ref401
	.byte $ff, $14
	.word @song0ref401
@song0ref446:
	.byte $86, $2b, $83, $8c, $2b, $c7, $86, $20, $85, $00, $81, $8c, $2a, $97, $2b, $2e, $a5, $2b, $a5, $23, $cd, $2f, $a5
	.byte $ff, $13
	.word @song0ref446
	.byte $ff, $13
	.word @song0ref446
	.byte $ff, $13
	.word @song0ref446
	.byte $ff, $13
	.word @song0ref446
	.byte $ff, $13
	.word @song0ref446
	.byte $ff, $13
	.word @song0ref446
	.byte $ff, $13
	.word @song0ref446
@song0ref490:
	.byte $30, $a5, $8e, $24, $91, $8c, $31, $91, $8e, $38, $91, $23, $91, $8c, $36, $b9, $8e, $2e, $91, $8c, $36, $a5, $28, $91
	.byte $00, $a5, $39, $91
	.byte $ff, $16
	.word @song0ref490
	.byte $ff, $16
	.word @song0ref490
	.byte $ff, $16
	.word @song0ref490
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref531:
	.byte $25, $f7, $a5, $27, $f3, $00, $25, $a5, $25, $f7, $a5, $27, $f7, $a5, $25, $f7, $a5, $29, $f5, $25, $a5, $25, $f7, $a5
	.byte $29, $f5, $25, $a5
	.byte $ff, $1c
	.word @song0ref531
	.byte $ff, $1c
	.word @song0ref531
	.byte $ff, $1c
	.word @song0ref531
@song0ref568:
	.byte $25, $91, $25, $a5, $25, $a5, $25, $91, $25, $f5, $27, $cd
	.byte $ff, $0c
	.word @song0ref568
	.byte $ff, $0c
	.word @song0ref568
	.byte $ff, $0c
	.word @song0ref568
	.byte $ff, $0c
	.word @song0ref568
	.byte $ff, $0c
	.word @song0ref568
	.byte $ff, $0c
	.word @song0ref568
	.byte $ff, $0c
	.word @song0ref568
@song0ref601:
	.byte $25, $f7, $a5, $00, $f5, $25, $a5, $25, $f7, $a5, $00, $f5, $25, $a5
	.byte $ff, $0e
	.word @song0ref601
	.byte $fd
	.word @song0ch4loop
@song1ch0:
@song1ch0loop:
	.byte $6a, .lobyte(@tempo_env_8_mid), .hibyte(@tempo_env_8_mid), $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b
	.byte $f7, $f7, $cf, $6b, $84
@song1ref22:
	.byte $33, $f7, $85, $36, $f7, $85, $39, $bd, $6b, $3a, $f7, $85, $33, $f7, $85, $36, $bd
@song1ref39:
	.byte $6b, $35, $f7, $85, $2e, $f7, $85, $31, $bd, $6b, $30, $f7, $85, $30, $f7, $85, $33, $bd, $6b, $31, $f7, $85, $2e, $f7
	.byte $85, $31, $bd, $6b, $30, $f7, $85, $35, $f7, $85, $36, $bd, $6b
	.byte $ff, $20
	.word @song1ref22
	.byte $ff, $13
	.word @song1ref39
	.byte $30, $f7, $85, $31, $9d, $33, $9d, $6b, $35, $f7, $85, $2c, $f7, $85, $31, $bd, $6b, $2e, $bd, $00, $bd, $2e, $bd, $00
	.byte $bd, $31, $bd, $6b, $2e, $bd, $00, $bd, $2e, $bd, $00, $f7, $85, $fd
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
@song1ref123:
	.byte $86, $1b, $99, $8a, $24, $81, $86, $1c, $99, $8a, $1b, $81, $86, $1b, $99, $8a, $1c, $81, $86, $1c, $99, $8a, $1b, $81
	.byte $86, $1b, $99, $8a, $1c, $81, $86, $1e, $99, $8a, $1b, $81, $86, $1b, $99, $8a, $1e, $81, $86, $1e, $99, $8a, $1b, $81
	.byte $86, $1b, $99, $8a, $1e, $81, $86, $20, $99, $8a, $1b, $81, $86, $1b, $99, $8a, $20, $81, $86, $21, $99, $8a, $1b, $81
	.byte $86, $1b, $99, $8a, $21, $81, $86, $21, $99, $8a, $1b, $81, $86, $1b, $99, $8a, $21, $81, $86, $22, $99, $8a, $1b, $81
	.byte $86, $1b, $99, $8a, $22, $81, $86, $22, $99, $8a, $1b, $81, $86, $1b, $99, $8a, $22, $81, $86, $23, $99, $8a, $1b, $81
	.byte $ff, $50
	.word @song1ref123
	.byte $ff, $50
	.word @song1ref123
@song1ref249:
	.byte $86
@song1ref250:
	.byte $16, $99, $8a, $23, $81, $86, $18, $99, $8a, $16, $81, $86, $16, $99, $8a, $18, $81, $86, $18, $99, $8a, $16, $81, $86
	.byte $16, $99, $8a, $18, $81, $86, $19, $99, $8a, $16, $81, $86, $16, $99, $8a, $19, $81, $86, $19, $99, $8a, $16, $81, $86
	.byte $16, $99, $8a, $19, $81, $86, $19, $99, $8a, $16, $81, $86, $16, $99, $8a, $19, $81, $86, $1b, $99, $8a, $16, $81, $86
	.byte $16, $99, $8a, $1b, $81, $86, $1b, $99, $8a, $16, $81, $86, $16, $99, $8a, $1b, $81, $86, $1d, $99, $8a, $16, $81, $86
	.byte $16, $99, $8a, $1d, $81, $86, $1d, $99, $8a, $16, $81, $86, $16, $99, $8a, $1d, $81, $86, $1d, $99, $8a, $16, $81
	.byte $ff, $50
	.word @song1ref249
	.byte $ff, $50
	.word @song1ref123
	.byte $ff, $50
	.word @song1ref249
	.byte $ff, $50
	.word @song1ref249
	.byte $86
@song1ref382:
	.byte $11, $99
@song1ref384:
	.byte $18, $81, $18, $99, $11, $81, $11, $99, $18, $81, $18, $99, $11, $81, $11, $99, $00, $81, $18, $99, $00, $81
	.byte $ff, $12
	.word @song1ref382
	.byte $ff, $16
	.word @song1ref384
	.byte $ff, $10
	.word @song1ref382
	.byte $ff, $50
	.word @song1ref250
	.byte $fd
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $80
@song1ref423:
	.byte $1b, $f5, $00, $85, $1b, $f5, $00, $85, $1b, $b5, $00, $85, $1b, $f5, $00, $85, $1b, $f5, $00, $85, $1b, $b5, $00, $85
	.byte $1e, $f5, $00, $85, $1e, $f5, $00, $85, $1e, $b5, $00, $85, $1e, $f5, $00, $85, $1e, $f5, $00, $85, $1e, $b5, $00, $85
	.byte $ff, $18
	.word @song1ref423
@song1ref474:
	.byte $16, $f5, $00, $85, $16, $f5, $00, $85, $16, $b5, $00, $85, $16, $f5, $00, $85, $16, $f5, $00, $85, $16, $b5, $00, $85
	.byte $ff, $18
	.word @song1ref474
	.byte $ff, $18
	.word @song1ref423
	.byte $ff, $18
	.word @song1ref474
	.byte $ff, $18
	.word @song1ref474
	.byte $1d, $f7, $f7, $8d, $1b, $9d, $1f, $9d, $1d, $f7, $f7, $8d, $1b, $9d, $1f, $9d
	.byte $ff, $18
	.word @song1ref474
	.byte $fd
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
@song1ref533:
	.byte $86
@song1ref534:
	.byte $25, $9d, $2b, $9d, $1e, $9d, $8c, $2d, $9d, $86, $25, $9d, $24, $9d, $20, $9d, $1e, $9d, $25, $9d, $29, $9d
	.byte $ff, $14
	.word @song1ref534
	.byte $ff, $14
	.word @song1ref534
@song1ref562:
	.byte $25, $9d, $2b, $9d, $26, $9d, $8c, $2d, $9d, $86, $25, $9d, $24, $9d, $90, $27, $9d, $8c, $27, $dd
	.byte $ff, $14
	.word @song1ref533
	.byte $ff, $14
	.word @song1ref534
	.byte $ff, $14
	.word @song1ref534
	.byte $ff, $14
	.word @song1ref534
	.byte $ff, $14
	.word @song1ref534
	.byte $ff, $10
	.word @song1ref562
	.byte $ff, $14
	.word @song1ref533
	.byte $ff, $14
	.word @song1ref534
	.byte $ff, $14
	.word @song1ref534
	.byte $ff, $14
	.word @song1ref534
	.byte $ff, $14
	.word @song1ref534
	.byte $ff, $10
	.word @song1ref562
	.byte $ff, $14
	.word @song1ref533
	.byte $ff, $14
	.word @song1ref534
	.byte $ff, $14
	.word @song1ref534
	.byte $ff, $10
	.word @song1ref562
	.byte $fd
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
@song1ref634:
	.byte $25, $f7, $85, $25, $f7, $85, $25, $bd, $25, $f7, $85, $25, $f7, $85, $25, $bd
	.byte $ff, $10
	.word @song1ref634
	.byte $ff, $10
	.word @song1ref634
	.byte $ff, $10
	.word @song1ref634
	.byte $ff, $10
	.word @song1ref634
	.byte $ff, $10
	.word @song1ref634
	.byte $ff, $10
	.word @song1ref634
	.byte $ff, $10
	.word @song1ref634
	.byte $ff, $10
	.word @song1ref634
	.byte $ff, $10
	.word @song1ref634
	.byte $fd
	.word @song1ch4loop
@song2ch0:
@song2ch0loop:
	.byte $6a, .lobyte(@tempo_env_18_mid), .hibyte(@tempo_env_18_mid), $f7, $f7, $f7, $f7, $df, $6b, $90
@song2ref12:
	.byte $27, $f7, $95, $2e, $f7, $95, $2a, $f7, $dd, $29, $a1, $27, $a1, $6b, $29, $f7, $dd, $25, $c5, $27, $f7, $f7, $ad, $6b
	.byte $ff, $16
	.word @song2ref12
	.byte $6b, $29, $f7, $95, $30, $f7, $95, $2e, $f7, $95, $31, $f7, $95, $6b, $30, $f7, $f7, $f7, $f7, $dd, $6b, $34, $a1, $33
	.byte $a1, $31, $a1, $30, $f7, $95, $31, $a1, $2c, $f7, $95, $34, $f7, $95, $6b, $31, $f7, $f7, $f7, $f7, $b9, $00, $a1, $fd
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
@song2ref90:
	.byte $82, $16, $9d, $90, $27, $81, $82, $27, $9d, $90, $22
@song2ref101:
	.byte $81, $82, $29, $9d, $90, $27, $81, $82, $27, $9d, $90, $29, $81
	.byte $ff, $10
	.word @song2ref90
	.byte $ff, $10
	.word @song2ref90
	.byte $ff, $10
	.word @song2ref90
	.byte $ff, $10
	.word @song2ref90
	.byte $ff, $10
	.word @song2ref90
	.byte $82, $12, $9d, $90, $27, $81, $82, $27, $9d, $90, $1e
	.byte $ff, $09
	.word @song2ref101
	.byte $ff, $10
	.word @song2ref90
	.byte $82, $11, $9d, $90, $27, $81, $82, $27, $9d, $90, $1d
	.byte $ff, $09
	.word @song2ref101
	.byte $82, $14, $9d, $90, $27, $81, $82, $27, $9d, $90, $20
	.byte $ff, $09
	.word @song2ref101
	.byte $ff, $10
	.word @song2ref90
	.byte $ff, $10
	.word @song2ref90
	.byte $ff, $10
	.word @song2ref90
	.byte $ff, $10
	.word @song2ref90
	.byte $82, $12, $9d, $90, $27, $81, $82, $27, $9d, $90, $1e
	.byte $ff, $09
	.word @song2ref101
	.byte $ff, $10
	.word @song2ref90
	.byte $82, $11, $9d, $90, $27, $81, $82, $27, $9d, $90, $1d
	.byte $ff, $09
	.word @song2ref101
	.byte $82, $14, $9d, $90, $27, $81, $82, $27, $9d, $90, $20
	.byte $ff, $09
	.word @song2ref101
	.byte $ff, $10
	.word @song2ref90
	.byte $ff, $10
	.word @song2ref90
@song2ref237:
	.byte $82, $18, $9d, $90, $29, $81, $82, $29, $9d, $90, $24
@song2ref248:
	.byte $81, $82, $2a, $9d, $90, $29, $81, $82, $29, $9d, $90, $2a, $81
	.byte $ff, $10
	.word @song2ref237
	.byte $82, $16, $9d, $90, $29, $81, $82, $29, $9d, $90, $22
	.byte $ff, $09
	.word @song2ref248
	.byte $82, $19, $9d, $90, $29, $81, $82, $29, $9d, $90, $25
	.byte $ff, $09
	.word @song2ref248
	.byte $ff, $10
	.word @song2ref237
	.byte $ff, $10
	.word @song2ref237
	.byte $ff, $10
	.word @song2ref237
	.byte $82, $18, $9d, $90, $29, $81, $82, $29, $9d, $90, $25
	.byte $ff, $09
	.word @song2ref248
@song2ref315:
	.byte $82, $19, $9d, $90, $2c, $81, $82, $2c, $9d, $90, $25
@song2ref326:
	.byte $81, $82, $2d, $9d, $90, $2c, $81, $82, $2c, $9d, $90, $2d, $81
	.byte $ff, $10
	.word @song2ref315
	.byte $82, $17, $9d, $90, $2c, $81, $82, $2c, $9d, $90, $23
	.byte $ff, $09
	.word @song2ref326
	.byte $82, $1a, $9d, $90, $2c, $81, $82, $2c, $9d, $90, $26
	.byte $ff, $09
	.word @song2ref326
	.byte $ff, $10
	.word @song2ref315
	.byte $ff, $10
	.word @song2ref315
	.byte $ff, $10
	.word @song2ref315
	.byte $ff, $10
	.word @song2ref315
	.byte $fd
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
	.byte $f7, $f7, $f7, $f7, $df, $80
@song2ref392:
	.byte $1b, $f7, $95, $22, $f7, $95, $1e, $f7, $95, $22, $f7, $95, $1d, $f7, $95, $20, $f7, $95, $22, $f7, $95, $22, $f7, $95
	.byte $ff, $18
	.word @song2ref392
	.byte $24, $f7, $95, $24, $f7, $95, $22, $f7, $95, $25, $f7, $95, $24, $f7, $f7, $f7, $f7, $dd, $28, $a1, $27, $a1, $25, $a1
	.byte $24, $f7, $95, $25, $a1, $20, $f7, $95, $28, $f7, $95, $25, $f7, $f7, $f7, $f7, $b9, $00, $a1, $fd
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
@song2ref466:
	.byte $84, $20, $c5, $82, $2f, $a1, $2f, $a1, $2f, $a1, $2f, $a1, $3e, $a1, $2f, $a1, $2f, $a1, $2f, $a1, $2f, $a1, $2f, $a1
	.byte $2f, $a1, $2f, $a1, $8c, $36, $c5
	.byte $ff, $1c
	.word @song2ref466
	.byte $ff, $1c
	.word @song2ref466
	.byte $ff, $1c
	.word @song2ref466
	.byte $ff, $1c
	.word @song2ref466
	.byte $ff, $1c
	.word @song2ref466
	.byte $ff, $1c
	.word @song2ref466
	.byte $ff, $1c
	.word @song2ref466
	.byte $ff, $1c
	.word @song2ref466
	.byte $fd
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
@song2ref525:
	.byte $25, $e9, $25, $a1, $25, $f7, $95, $25, $e9, $25, $a1, $25, $f7, $95
	.byte $ff, $0e
	.word @song2ref525
	.byte $ff, $0e
	.word @song2ref525
	.byte $ff, $0e
	.word @song2ref525
	.byte $ff, $0e
	.word @song2ref525
	.byte $ff, $0e
	.word @song2ref525
	.byte $ff, $0e
	.word @song2ref525
	.byte $ff, $0e
	.word @song2ref525
	.byte $ff, $0e
	.word @song2ref525
	.byte $fd
	.word @song2ch4loop
@song3ch0:
@song3ch0loop:
	.byte $6a, .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid), $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $84
@song3ref14:
	.byte $33, $b9, $35, $91, $33, $91, $32, $91, $33, $91, $35, $91, $36, $b9, $36, $91, $38, $b9, $38, $91, $6b, $35, $b9, $35
	.byte $91, $3a, $b9, $3a, $91, $3b, $91, $3a, $91, $38, $91, $36, $91, $3a, $91, $38, $91, $36, $91, $35, $91, $6b
	.byte $ff, $1d
	.word @song3ref14
	.byte $b9, $3b, $91, $3e, $b9, $3e, $91, $6b, $3f, $cd, $00, $f7, $f5
@song3ref76:
	.byte $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf
	.byte $ff, $0c
	.word @song3ref76
	.byte $6b, $f7, $f7, $cf, $fd
	.word @song3ch0loop
@song3ch1:
@song3ch1loop:
	.byte $f7, $f7, $cf, $f7, $f7, $cf, $90
@song3ref110:
	.byte $36, $b9, $38, $91, $36, $91, $35, $91, $36, $91, $38, $91, $3a, $b9, $00, $91, $41, $cd, $3f, $cd, $3e, $cd, $3f, $cd
	.byte $41, $cd
	.byte $ff, $1a
	.word @song3ref110
@song3ref139:
	.byte $00, $f7, $f7, $cd
@song3ref143:
	.byte $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf
	.byte $ff, $0c
	.word @song3ref143
	.byte $f7, $f7, $cf, $fd
	.word @song3ch1loop
@song3ch2:
@song3ch2loop:
	.byte $90
@song3ref166:
	.byte $1b, $91, $00, $91, $1b, $91, $00, $a5, $1b, $91, $00, $91, $1b, $91, $1e, $91, $00, $91, $1e, $91, $00, $a5, $1e, $91
	.byte $00, $91, $20, $91, $1d, $91, $00, $91, $1d, $91, $00, $a5, $1d, $91, $00, $91, $1e, $91, $20, $91, $00, $91, $20, $91
	.byte $00, $a5, $20, $91, $00, $91, $22, $91
	.byte $ff, $38
	.word @song3ref166
	.byte $ff, $38
	.word @song3ref166
	.byte $ff, $0e
	.word @song3ref166
	.byte $1b, $91, $00, $91, $1b, $91, $00, $e1
	.byte $ff, $0e
	.word @song3ref166
	.byte $1b, $91, $00, $91, $1b, $91, $00, $e1
	.byte $ff, $0c
	.word @song3ref143
	.byte $ff, $0c
	.word @song3ref143
	.byte $fd
	.word @song3ch2loop
@song3ch3:
@song3ch3loop:
@song3ref260:
	.byte $8a, $2c, $91, $2e, $8b, $86, $2e, $83, $8a, $2c, $91, $2e, $8b, $86, $2e, $83, $8a, $2c, $91, $2e, $91, $86, $33, $91
	.byte $2e, $91, $8a, $2c, $91, $2e, $91, $2c, $91, $2e, $91, $86, $2c, $91, $80, $33, $91, $2e, $91, $33, $91
	.byte $ff, $24
	.word @song3ref260
	.byte $ff, $24
	.word @song3ref260
	.byte $ff, $24
	.word @song3ref260
	.byte $ff, $24
	.word @song3ref260
	.byte $ff, $24
	.word @song3ref260
	.byte $ff, $24
	.word @song3ref260
	.byte $ff, $24
	.word @song3ref260
	.byte $ff, $10
	.word @song3ref139
	.byte $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $fd
	.word @song3ch3loop
@song3ch4:
@song3ch4loop:
@song3ref342:
	.byte $25, $cd, $25, $91, $00, $b9, $25, $91, $00, $b9, $25, $91, $00, $b9
	.byte $ff, $0e
	.word @song3ref342
	.byte $ff, $0e
	.word @song3ref342
	.byte $ff, $0e
	.word @song3ref342
	.byte $ff, $0e
	.word @song3ref342
	.byte $ff, $0e
	.word @song3ref342
	.byte $ff, $0e
	.word @song3ref342
	.byte $ff, $0e
	.word @song3ref342
	.byte $ff, $0c
	.word @song3ref143
	.byte $ff, $0c
	.word @song3ref143
	.byte $fd
	.word @song3ch4loop
@song4ch0:
@song4ch0loop:
	.byte $6a, .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid), $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf
	.byte $6b, $f7, $f7, $cf
@song4ref20:
	.byte $6b, $8c, $27, $cd, $29, $cd, $2a, $cd, $29, $cd, $6b, $2c, $cd, $29, $cd, $2a, $cd, $29, $cd, $6b, $27, $cd, $88, $36
	.byte $c3, $00, $87, $33, $c3, $00, $87, $36, $c3, $00, $87, $6b, $35, $c3, $00, $af, $32, $9b, $00, $87, $33, $c3, $00, $87
	.byte $35, $c3, $00, $87
	.byte $ff, $2e
	.word @song4ref20
	.byte $ff, $2e
	.word @song4ref20
	.byte $6b, $36, $cd, $00, $f7, $f5, $6b, $f7, $f7, $cf, $6b, $8c
@song4ref90:
	.byte $3e, $cd, $3b, $cd, $38, $cd, $36, $cd, $6b, $3a, $cd, $3d, $cd, $3c, $cd, $36, $cd, $6b, $35, $cd, $36, $cd, $33, $cd
	.byte $32, $cd, $6b, $33, $f7, $f7, $cd, $6b
	.byte $ff, $1c
	.word @song4ref90
	.byte $fd
	.word @song4ch0loop
@song4ch1:
@song4ch1loop:
	.byte $84
@song4ref130:
	.byte $0f, $f7, $f7, $cd, $00, $f7, $f7, $cd
	.byte $ff, $08
	.word @song4ref130
	.byte $ff, $08
	.word @song4ref130
@song4ref144:
	.byte $82, $20, $cd, $1e, $cd, $1b, $cd, $1e, $cd, $1d, $cd, $00, $a5, $1a, $a5, $1b, $cd, $1d, $cd, $88, $36, $cd, $00, $f7
	.byte $f5, $f7, $f7, $cf
	.byte $ff, $1a
	.word @song4ref144
	.byte $84
@song4ref176:
	.byte $0f, $f7, $f7, $cd, $0f, $f7, $f7, $cd
	.byte $ff, $08
	.word @song4ref176
	.byte $ff, $08
	.word @song4ref176
	.byte $ff, $08
	.word @song4ref176
	.byte $ff, $08
	.word @song4ref176
	.byte $ff, $08
	.word @song4ref176
	.byte $fd
	.word @song4ch1loop
@song4ch2:
@song4ch2loop:
@song4ref203:
	.byte $80
@song4ref204:
	.byte $1b, $9f, $00, $83, $1b, $a3, $00, $93, $1b, $91, $00, $91, $1b, $8d, $00, $81, $1b, $91, $00, $91, $1b, $9f, $00, $d3
	.byte $ff, $17
	.word @song4ref204
	.byte $83, $16, $cd
	.byte $ff, $18
	.word @song4ref204
	.byte $ff, $17
	.word @song4ref204
	.byte $83, $16, $cd
	.byte $ff, $18
	.word @song4ref204
	.byte $ff, $17
	.word @song4ref204
	.byte $83, $16, $cd
	.byte $ff, $18
	.word @song4ref204
	.byte $ff, $17
	.word @song4ref204
	.byte $83, $16, $cd
	.byte $ff, $18
	.word @song4ref204
	.byte $ff, $17
	.word @song4ref204
	.byte $83, $16, $cd
	.byte $ff, $18
	.word @song4ref204
	.byte $ff, $17
	.word @song4ref204
	.byte $83, $16, $cd, $23, $f7, $8f, $00, $23, $8f, $00, $23, $a3, $00, $23, $f5, $22, $f7, $f7, $cd
	.byte $ff, $18
	.word @song4ref204
	.byte $ff, $17
	.word @song4ref204
	.byte $83, $16, $cd
	.byte $ff, $18
	.word @song4ref204
	.byte $ff, $17
	.word @song4ref204
	.byte $83, $16, $cd
@song4ref313:
	.byte $1b, $a5, $1b, $91, $00, $cd, $1b, $89, $00, $85, $1b, $89, $00, $99, $1b, $89, $00, $e7, $8c, $26, $80
	.byte $ff, $13
	.word @song4ref313
	.byte $80
	.byte $ff, $13
	.word @song4ref313
	.byte $80
	.byte $ff, $13
	.word @song4ref313
	.byte $ff, $18
	.word @song4ref203
	.byte $ff, $18
	.word @song4ref204
	.byte $ff, $18
	.word @song4ref204
	.byte $ff, $17
	.word @song4ref204
	.byte $83, $16, $cd, $fd
	.word @song4ch2loop
@song4ch3:
@song4ch3loop:
@song4ref364:
	.byte $80, $0f, $87, $00, $87, $8e, $1e, $91, $20, $81, $8c, $20, $8d, $8e, $1f, $91, $80, $0f, $87, $00, $9b, $8e, $1e, $83
	.byte $8c, $1e, $8b, $21, $91, $80, $0f, $87, $00, $9b, $8e, $27, $91, $1e, $91, $80, $0f, $87, $8e, $20, $87, $1e, $91, $8c
	.byte $20, $91, $8e, $1d, $91
	.byte $ff, $28
	.word @song4ref364
	.byte $ff, $28
	.word @song4ref364
	.byte $ff, $28
	.word @song4ref364
	.byte $ff, $28
	.word @song4ref364
	.byte $ff, $28
	.word @song4ref364
	.byte $ff, $28
	.word @song4ref364
	.byte $ff, $28
	.word @song4ref364
	.byte $ff, $28
	.word @song4ref364
	.byte $ff, $28
	.word @song4ref364
	.byte $ff, $28
	.word @song4ref364
	.byte $ff, $28
	.word @song4ref364
@song4ref450:
	.byte $84, $10, $a5, $8a, $1c, $81, $8c, $20, $8d, $8a, $1c, $91, $00, $91, $1c, $91, $8e, $1e, $83, $8c, $1e, $8b, $8a, $1c
	.byte $91, $1c, $91, $00, $91, $1c, $91, $8e, $1e, $91, $8c, $28, $cd
	.byte $ff, $1c
	.word @song4ref450
	.byte $ff, $1c
	.word @song4ref450
	.byte $ff, $1c
	.word @song4ref450
	.byte $ff, $1c
	.word @song4ref450
	.byte $ff, $1c
	.word @song4ref450
	.byte $ff, $1c
	.word @song4ref450
	.byte $ff, $1c
	.word @song4ref450
	.byte $ff, $1c
	.word @song4ref450
	.byte $ff, $1c
	.word @song4ref450
	.byte $ff, $1c
	.word @song4ref450
	.byte $ff, $1c
	.word @song4ref450
	.byte $ff, $1c
	.word @song4ref450
	.byte $ff, $1c
	.word @song4ref450
	.byte $fd
	.word @song4ch3loop
@song4ch4:
@song4ch4loop:
@song4ref530:
	.byte $25, $f7, $a5, $27, $f7, $a5, $00, $f7, $a5, $27, $cd, $25, $cd
	.byte $ff, $0d
	.word @song4ref530
@song4ref546:
	.byte $25, $f7, $a5, $00, $f7, $a5, $25, $f7, $a5, $00, $cd, $25, $cd
	.byte $ff, $0d
	.word @song4ref530
	.byte $ff, $0d
	.word @song4ref546
	.byte $ff, $0d
	.word @song4ref530
@song4ref568:
	.byte $25, $cd, $00, $a5, $25, $a5, $25, $cd, $00, $a5, $25, $a5
	.byte $ff, $0c
	.word @song4ref568
	.byte $25, $f7, $a5, $27, $f7, $a5, $25, $f7, $a5, $27, $f7, $a5
	.byte $ff, $0a
	.word @song4ref546
	.byte $f7, $a5
	.byte $ff, $0a
	.word @song4ref546
	.byte $f7, $a5
	.byte $ff, $0a
	.word @song4ref546
	.byte $f7, $a5
	.byte $ff, $0a
	.word @song4ref546
	.byte $f7, $a5
	.byte $ff, $0a
	.word @song4ref546
	.byte $f7, $a5, $fd
	.word @song4ch4loop
@song5ch0:
@song5ch0loop:
	.byte $6a, .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid)
@song5ref5:
	.byte $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b
	.byte $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b
	.byte $ff, $18
	.word @song5ref5
	.byte $fd
	.word @song5ch0loop
@song5ch1:
@song5ch1loop:
@song5ref44:
	.byte $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf
	.byte $ff, $18
	.word @song5ref44
	.byte $fd
	.word @song5ch1loop
@song5ch2:
@song5ch2loop:
	.byte $ff, $18
	.word @song5ref44
	.byte $ff, $18
	.word @song5ref44
	.byte $fd
	.word @song5ch2loop
@song5ch3:
@song5ch3loop:
	.byte $ff, $18
	.word @song5ref44
	.byte $ff, $18
	.word @song5ref44
	.byte $fd
	.word @song5ch3loop
@song5ch4:
@song5ch4loop:
	.byte $ff, $18
	.word @song5ref44
	.byte $ff, $18
	.word @song5ref44
	.byte $fd
	.word @song5ch4loop
