; This file for the FamiStudio Sound Engine and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_the_trial_of_kharzoid_ost=music_data_the_trial_of_kharzoid_ost
.endif

music_data_the_trial_of_kharzoid_ost:
	.byte 7
	.word @instruments
	.word @samples-148
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4
	.byte .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid), 0, 0
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4
	.byte .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid), 0, 0
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4
	.byte .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid), 0, 0
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4
	.byte .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid), 0, 0
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4
	.byte .lobyte(@tempo_env_8_mid), .hibyte(@tempo_env_8_mid), 0, 0
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4
	.byte .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid), 0, 0
	.word @song6ch0,@song6ch1,@song6ch2,@song6ch3,@song6ch4
	.byte .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid), 0, 0

.export music_data_the_trial_of_kharzoid_ost
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.word @env17,@env0,@env11,@env8
	.word @env12,@env0,@env15,@env8
	.word @env6,@env0,@env13,@env8
	.word @env5,@env0,@env10,@env8
	.word @env16,@env0,@env18,@env8
	.word @env2,@env0,@env13,@env8
	.word @env3,@env0,@env11,@env8
	.word @env4,@env0,@env10,@env8
	.word @env7,@env0,@env13,@env14
	.word @env9,@env0,@env13,@env1

@samples:
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$9f,$0f,$40	;37 (sample_tom)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;38 
	.byte $28+.lobyte(FAMISTUDIO_DPCM_PTR),$a4,$0f,$40	;39 (sfx_voice_D)
	.byte $00+.lobyte(FAMISTUDIO_DPCM_PTR),$00,$00,$40	;40 
	.byte $51+.lobyte(FAMISTUDIO_DPCM_PTR),$a4,$0f,$40	;41 (sfx_voice_Em)

@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $00,$c0,$0d,$c1,$c1,$c0,$03,$bf,$bf,$c0,$03,$c1,$c1,$c0,$03,$c1,$05,$c0,$03,$bf,$04,$bf,$00,$0f
@env2:
	.byte $00,$c1,$c3,$03,$c4,$02,$c3,$02,$c2,$c2,$c1,$00,$0a
@env3:
	.byte $04,$c5,$7f,$00,$01
@env4:
	.byte $00,$c0,$c0,$c1,$0b,$c2,$02,$c3,$04,$c4,$04,$c5,$03,$c6,$c6,$c7,$02,$c8,$c9,$ca,$cb,$cb,$cc,$ce,$ce,$cf,$c7,$c7,$c6,$03,$c5,$c5,$c4,$c4,$c3,$03,$c2,$c2,$c1,$c1,$c0,$00,$28
@env5:
	.byte $00,$cf,$c4,$c5,$c6,$c7,$c8,$ca,$cb,$c4,$c3,$c4,$c4,$c5,$c6,$c8,$c9,$c2,$c1,$c2,$c3,$c4,$c5,$c6,$c7,$c0,$c0,$c1,$c2,$c3,$c4,$c5,$c0,$00,$20
@env6:
	.byte $00,$c6,$ca,$c7,$c5,$c5,$c4,$c3,$c1,$00,$08
@env7:
	.byte $09,$c1,$02,$c2,$c3,$c4,$c5,$00,$06,$c4,$c3,$c3,$c2,$c2,$c1,$02,$c0,$00,$10
@env8:
	.byte $00,$c0,$7f,$00,$01
@env9:
	.byte $14,$c3,$c4,$05,$c5,$06,$c6,$03,$c7,$02,$c8,$04,$c9,$02,$c8,$c8,$c7,$02,$00,$10,$c6,$c6,$c5,$c5,$c4,$c4,$c3,$02,$c2,$c2,$c1,$c1,$c0,$00,$20
@env10:
	.byte $7f,$00,$00
@env11:
	.byte $c2,$7f,$00,$00
@env12:
	.byte $00,$cb,$c9,$c8,$c6,$c6,$c5,$c4,$c3,$c9,$c6,$c5,$c4,$c2,$c2,$c1,$c0,$c6,$c4,$c3,$c2,$c2,$c1,$c1,$c0,$c4,$c3,$c2,$c1,$03,$c0,$00,$1e
@env13:
	.byte $c1,$7f,$00,$00
@env14:
	.byte $00,$c0,$07,$c1,$c1,$c0,$02,$bf,$bf,$c0,$03,$c1,$04,$c0,$03,$bf,$02,$bf,$00,$09
@env15:
	.byte $c2,$c1,$c0,$c1,$c2,$c1,$c0,$c1,$00,$07
@env16:
	.byte $00,$c8,$ce,$cc,$ca,$c9,$c9,$c8,$c8,$c7,$02,$c6,$c6,$c5,$c4,$c3,$02,$c2,$c2,$c1,$02,$c0,$00,$15
@env17:
	.byte $04,$c7,$7f,$00,$01
@env18:
	.byte $c0,$02,$c1,$02,$c0,$00,$04
@tempo_env_10_mid:
	.byte $03,$04,$06,$05,$05,$05,$80
@tempo_env_8_mid:
	.byte $03,$05,$04,$06,$05,$80
@song0ch0:
@song0ch0loop:
	.byte $6a, .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid), $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf
	.byte $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $90, $35, $cd, $6b, $00
	.byte $81, $3a, $f7, $f1, $38, $cd, $6b, $3a, $f7, $f5, $3c, $cd, $6b, $38, $f7, $f5, $36, $cd, $6b, $38, $f7, $f5, $35, $cd
	.byte $6b, $3a, $f7, $f5, $3c, $cd, $6b, $3d, $f7, $f5, $41, $cd, $6b, $3f, $cd, $62, $38, $f7, $a5, $3a, $cd, $6b, $3c, $f7
	.byte $f5, $41, $cd, $6b, $00, $f7, $f7, $cd, $6b, $46, $f7, $f7, $cd, $6b, $46, $f7, $f7, $cd, $6b, $46, $f7, $f7, $cd, $6b
	.byte $8a
@song0ref113:
	.byte $43, $8b, $44, $89, $45, $8b, $46, $8b, $45, $89, $44, $8b, $43, $8b, $44, $89, $45, $8b, $46, $8b, $45, $89, $44, $8b
	.byte $ff, $18
	.word @song0ref113
	.byte $6b
	.byte $ff, $18
	.word @song0ref113
	.byte $ff, $18
	.word @song0ref113
	.byte $6b
	.byte $ff, $18
	.word @song0ref113
	.byte $ff, $18
	.word @song0ref113
	.byte $6b
	.byte $ff, $18
	.word @song0ref113
	.byte $ff, $18
	.word @song0ref113
	.byte $6b, $00, $f7, $f7, $cd, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
	.byte $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $92
@song0ref195:
	.byte $1b, $f7, $f3, $00, $81, $1d, $cb, $1e, $f7, $f7, $20, $c9, $00, $85, $1d, $f7, $f1, $1b, $c9, $00, $1d, $f7, $f5, $19
	.byte $cd
	.byte $ff, $19
	.word @song0ref195
	.byte $ff, $19
	.word @song0ref195
	.byte $90
@song0ref227:
	.byte $46, $f7, $f7, $c9, $00, $81, $45, $f7, $f7, $cd, $44, $f7, $f7, $cd, $43, $f7, $f7, $cd
	.byte $ff, $12
	.word @song0ref227
	.byte $00, $f7, $f7, $cd, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80
@song0ref266:
	.byte $1b, $81, $1b, $a1, $1e, $81, $1b, $a1, $22, $81, $1b, $a1, $27, $81, $1b, $a1, $2e, $81, $1b, $f7, $a1
	.byte $ff, $15
	.word @song0ref266
@song0ref290:
	.byte $1d, $81, $1d, $a1, $20, $81, $1d, $a1, $24, $81, $1d, $9f, $00, $29, $81, $1d, $a1, $2c, $81, $1d, $f7, $a1
	.byte $ff, $16
	.word @song0ref290
	.byte $ff, $15
	.word @song0ref266
	.byte $ff, $15
	.word @song0ref266
	.byte $ff, $16
	.word @song0ref290
	.byte $ff, $16
	.word @song0ref290
	.byte $ff, $15
	.word @song0ref266
	.byte $ff, $15
	.word @song0ref266
	.byte $ff, $16
	.word @song0ref290
	.byte $ff, $16
	.word @song0ref290
	.byte $ff, $15
	.word @song0ref266
	.byte $ff, $15
	.word @song0ref266
	.byte $ff, $16
	.word @song0ref290
	.byte $ff, $16
	.word @song0ref290
	.byte $ff, $15
	.word @song0ref266
	.byte $ff, $15
	.word @song0ref266
	.byte $ff, $15
	.word @song0ref266
	.byte $ff, $15
	.word @song0ref266
	.byte $ff, $15
	.word @song0ref266
	.byte $ff, $15
	.word @song0ref266
	.byte $ff, $15
	.word @song0ref266
	.byte $ff, $15
	.word @song0ref266
	.byte $ff, $15
	.word @song0ref266
	.byte $ff, $15
	.word @song0ref266
	.byte $ff, $15
	.word @song0ref266
	.byte $ff, $15
	.word @song0ref266
	.byte $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref391:
	.byte $88, $2f, $cd, $2e, $cd, $2f, $cd, $2e, $83, $8e, $2e, $c7, $88, $2f, $cd, $2e, $cd, $2f, $cd, $2e, $83, $8e, $2e, $c7
	.byte $ff, $14
	.word @song0ref391
	.byte $ff, $14
	.word @song0ref391
	.byte $ff, $14
	.word @song0ref391
	.byte $ff, $14
	.word @song0ref391
	.byte $ff, $14
	.word @song0ref391
	.byte $ff, $14
	.word @song0ref391
	.byte $ff, $14
	.word @song0ref391
@song0ref436:
	.byte $88, $2b, $83, $8e, $2b, $c7, $88, $20, $85, $00, $81, $8e, $2a, $97, $2b, $2e, $a5, $2b, $a5, $23, $cd, $2f, $a5
	.byte $ff, $13
	.word @song0ref436
	.byte $ff, $13
	.word @song0ref436
	.byte $ff, $13
	.word @song0ref436
	.byte $ff, $13
	.word @song0ref436
	.byte $ff, $13
	.word @song0ref436
	.byte $ff, $13
	.word @song0ref436
	.byte $ff, $13
	.word @song0ref436
@song0ref480:
	.byte $30, $a5, $90, $24, $91, $8e, $31, $91, $90, $38, $91, $23, $91, $8e, $36, $b9, $90, $2e, $91, $8e, $36, $a5, $28, $91
	.byte $00, $a5, $39, $91
	.byte $ff, $16
	.word @song0ref480
	.byte $ff, $16
	.word @song0ref480
	.byte $ff, $16
	.word @song0ref480
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref521:
	.byte $25, $f7, $a5, $27, $f3, $00, $25, $a5, $25, $f7, $a5, $27, $f7, $a5, $25, $f7, $a5, $29, $f5, $25, $a5, $25, $f7, $a5
	.byte $29, $f5, $25, $a5
	.byte $ff, $1c
	.word @song0ref521
	.byte $ff, $1c
	.word @song0ref521
	.byte $ff, $1c
	.word @song0ref521
@song0ref558:
	.byte $25, $91, $25, $a5, $25, $a5, $25, $91, $25, $f5, $27, $cd, $25, $91, $25, $a5, $25, $a5, $25, $91, $25, $f5, $27, $cd
	.byte $ff, $18
	.word @song0ref558
	.byte $ff, $18
	.word @song0ref558
	.byte $ff, $18
	.word @song0ref558
@song0ref591:
	.byte $25, $f7, $a5, $00, $f5, $25, $a5, $25, $f7, $a5, $00, $f5, $25, $a5
	.byte $ff, $0e
	.word @song0ref591
	.byte $fd
	.word @song0ch4loop
@song1ch0:
@song1ch0loop:
	.byte $6a, .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid), $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf
	.byte $6b, $f7, $f7, $cf
@song1ref20:
	.byte $6b, $8e, $27, $cd, $29, $cd, $2a, $cd, $29, $cd, $6b, $2c, $cd, $29, $cd, $2a, $cd, $29, $cd, $6b, $27, $cd, $8a, $42
	.byte $c3, $00, $87, $3f, $c3, $00, $87, $42, $c3, $00, $87, $6b, $41, $c3, $00, $af, $3e, $9b, $00, $87, $3f, $c3, $00, $87
	.byte $41, $c3, $00, $87
	.byte $ff, $2e
	.word @song1ref20
	.byte $ff, $2e
	.word @song1ref20
	.byte $6b, $42, $cd, $00, $f7, $f5, $6b, $f7, $f7, $cf, $6b, $8e
@song1ref90:
	.byte $3e, $cd, $3b, $cd, $38, $cd, $36, $cd, $6b, $3a, $cd, $3d, $cd, $3c, $cd, $36, $cd, $6b, $35, $cd, $36, $cd, $33, $cd
	.byte $32, $cd, $6b, $33, $f7, $f7, $cd, $6b
	.byte $ff, $1c
	.word @song1ref90
	.byte $fd
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $86
@song1ref130:
	.byte $0f, $f7, $f7, $cd, $00, $f7, $f7, $cd
	.byte $ff, $08
	.word @song1ref130
	.byte $ff, $08
	.word @song1ref130
@song1ref144:
	.byte $84, $20, $cd, $1e, $cd, $1b, $cd, $1e, $cd, $1d, $cd, $00, $a5, $1a, $a5, $1b, $cd, $1d, $cd, $8a, $42, $cd, $00, $f7
	.byte $f5, $f7, $f7, $cf
	.byte $ff, $1a
	.word @song1ref144
	.byte $86
@song1ref176:
	.byte $0f, $f7, $f7, $cd, $0f, $f7, $f7, $cd
	.byte $ff, $08
	.word @song1ref176
	.byte $ff, $08
	.word @song1ref176
	.byte $ff, $08
	.word @song1ref176
	.byte $ff, $08
	.word @song1ref176
	.byte $ff, $08
	.word @song1ref176
	.byte $fd
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $80
@song1ref204:
	.byte $1b, $9f, $00, $83, $1b, $a3, $00, $bb, $1b, $8d, $00, $81, $1b, $91, $00, $91, $1b, $9f, $00, $d3
	.byte $ff, $13
	.word @song1ref204
	.byte $83, $16, $cd
	.byte $ff, $14
	.word @song1ref204
	.byte $ff, $13
	.word @song1ref204
	.byte $83, $16, $cd
	.byte $ff, $14
	.word @song1ref204
	.byte $ff, $13
	.word @song1ref204
	.byte $83, $16, $cd
	.byte $ff, $14
	.word @song1ref204
	.byte $ff, $13
	.word @song1ref204
	.byte $83, $16, $cd
	.byte $ff, $14
	.word @song1ref204
	.byte $ff, $13
	.word @song1ref204
	.byte $83, $16, $cd
	.byte $ff, $14
	.word @song1ref204
	.byte $ff, $13
	.word @song1ref204
	.byte $83, $16, $cd, $23, $f7, $8f, $00, $23, $8f, $00, $23, $a3, $00, $23, $f5, $22, $f7, $f7, $cd
	.byte $ff, $14
	.word @song1ref204
	.byte $ff, $13
	.word @song1ref204
	.byte $83, $16, $cd
	.byte $ff, $14
	.word @song1ref204
	.byte $ff, $13
	.word @song1ref204
	.byte $83, $16, $cd
@song1ref309:
	.byte $1b, $a5, $1b, $91, $00, $cd, $1b, $89, $00, $85, $1b, $89, $00, $99, $1b, $89, $00, $e9
	.byte $ff, $12
	.word @song1ref309
	.byte $ff, $12
	.word @song1ref309
	.byte $ff, $12
	.word @song1ref309
	.byte $ff, $14
	.word @song1ref204
	.byte $ff, $14
	.word @song1ref204
	.byte $ff, $14
	.word @song1ref204
	.byte $ff, $13
	.word @song1ref204
	.byte $83, $16, $cd, $fd
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
@song1ref355:
	.byte $80, $0f, $87, $00, $87, $90, $1e, $91, $20, $81, $8e, $20, $8d, $90, $1f, $91, $80, $0f, $87, $00, $9b, $90, $1e, $83
	.byte $8e, $1e, $8b, $21, $91, $80, $0f, $87, $00, $9b, $90, $27, $91, $1e, $91, $80, $0f, $87, $90, $20, $87, $1e, $91, $8e
	.byte $20, $91, $90, $1d, $91
	.byte $ff, $28
	.word @song1ref355
	.byte $ff, $28
	.word @song1ref355
	.byte $ff, $28
	.word @song1ref355
	.byte $ff, $28
	.word @song1ref355
	.byte $ff, $28
	.word @song1ref355
	.byte $ff, $28
	.word @song1ref355
	.byte $ff, $28
	.word @song1ref355
	.byte $ff, $28
	.word @song1ref355
	.byte $ff, $28
	.word @song1ref355
	.byte $ff, $28
	.word @song1ref355
	.byte $ff, $28
	.word @song1ref355
@song1ref441:
	.byte $86, $10, $a5, $8c, $1d, $81, $8e, $20, $8d, $8c, $1d, $87, $00, $9b, $1d, $91, $90, $1e, $83, $8e, $1e, $8b, $8c, $1c
	.byte $87, $00, $87, $1d, $91, $1c, $00, $8f, $1d, $91, $90, $1e, $91, $8e, $28, $cd
	.byte $ff, $1f
	.word @song1ref441
	.byte $ff, $1f
	.word @song1ref441
	.byte $ff, $1f
	.word @song1ref441
	.byte $ff, $1f
	.word @song1ref441
	.byte $ff, $1f
	.word @song1ref441
	.byte $ff, $1f
	.word @song1ref441
	.byte $ff, $1f
	.word @song1ref441
	.byte $ff, $1f
	.word @song1ref441
	.byte $ff, $1f
	.word @song1ref441
	.byte $ff, $1f
	.word @song1ref441
	.byte $ff, $1f
	.word @song1ref441
	.byte $ff, $1f
	.word @song1ref441
	.byte $ff, $1f
	.word @song1ref441
	.byte $fd
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
@song1ref524:
	.byte $25, $f7, $a5, $27, $f7, $a5, $00, $f7, $a5, $27, $cd, $25, $cd
	.byte $ff, $0d
	.word @song1ref524
@song1ref540:
	.byte $25, $f7, $a5, $00, $f7, $a5, $25, $f7, $a5, $00, $cd, $25, $cd
	.byte $ff, $0d
	.word @song1ref524
	.byte $ff, $0d
	.word @song1ref540
	.byte $ff, $0d
	.word @song1ref524
@song1ref562:
	.byte $25, $cd, $00, $a5, $25, $a5, $25, $cd, $00, $a5, $25, $a5
	.byte $ff, $0c
	.word @song1ref562
	.byte $25, $f7, $a5, $27, $f7, $a5, $25, $f7, $a5, $27, $f7, $a5
	.byte $ff, $0a
	.word @song1ref540
	.byte $f7, $a5
	.byte $ff, $0a
	.word @song1ref540
	.byte $f7, $a5
	.byte $ff, $0a
	.word @song1ref540
	.byte $f7, $a5
	.byte $ff, $0a
	.word @song1ref540
	.byte $f7, $a5
	.byte $ff, $0a
	.word @song1ref540
	.byte $f7, $a5, $fd
	.word @song1ch4loop
@song2ch0:
@song2ch0loop:
	.byte $6a, .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid), $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $8c
@song2ref14:
	.byte $0f, $a5, $10, $8d, $00, $81, $10, $91, $0f, $91, $10, $91, $00, $cd, $10, $a1, $00, $81, $0f, $a1, $00, $81, $10, $8d
	.byte $00, $81, $10, $8d, $00, $81, $6b
	.byte $ff, $1e
	.word @song2ref14
	.byte $6b, $1b, $a5, $1c, $8d, $00, $81, $1c, $91, $1b, $91, $1c, $91, $00, $91, $1e, $91, $84, $0f, $91, $00, $91, $8c, $1c
	.byte $a1, $00, $81, $1b
@song2ref76:
	.byte $a1, $00, $81, $1c, $8d, $00, $81, $1c, $8d, $00, $81, $6b, $1e
	.byte $ff, $0b
	.word @song2ref76
	.byte $1e, $8d, $00, $81, $1c, $8d, $00, $81, $19, $8d, $00, $95, $20, $91, $84, $1b, $91, $00, $91, $23, $91, $0f, $91, $3f
	.byte $91, $1b, $91, $40, $91, $6b, $00, $f7, $f7, $cd, $6b, $f7, $f7, $cf, $6b, $92
@song2ref132:
	.byte $14, $9f, $00, $83, $14, $a1, $00, $a9, $14, $a1, $00, $a9, $14, $8f, $00, $93, $14, $a1, $00, $a9, $6b
	.byte $ff, $14
	.word @song2ref132
	.byte $6b, $8c, $20, $a5, $21, $8d, $00, $81, $21, $91, $20, $91, $21, $91, $00, $91, $23, $91, $84, $14, $91, $00, $91, $8c
	.byte $21, $a1, $00, $81, $20
@song2ref185:
	.byte $a1, $00, $81, $21, $8d, $00, $81, $21, $8d, $00, $81, $6b, $23
	.byte $ff, $0b
	.word @song2ref185
	.byte $23, $8d, $00, $81, $21, $8d, $00, $81, $20, $8d, $00, $95, $25, $91, $84, $20, $91, $00, $91, $28, $91, $14, $91, $44
	.byte $91, $20, $91, $45, $91, $6b, $00, $f7, $f7, $cd, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf, $fd
	.word @song2ch0loop
@song2ch1:
@song2ch1loop:
	.byte $f7, $f7, $cf, $f7, $f7, $cf
@song2ref257:
	.byte $00, $81, $92
@song2ref260:
	.byte $27, $f7, $c9, $2a, $a5, $2e, $cd, $cf, $2f, $a5, $2e, $a5, $2c, $a5, $2f, $a5, $2e, $cd, $27, $f7, $f7, $a5, $f9, $a5
	.byte $00, $f7, $f7, $cd, $00, $81
	.byte $ff, $10
	.word @song2ref260
@song2ref293:
	.byte $32, $cd, $33, $f7, $f5, $84, $38, $cd, $34, $cd, $31, $cd, $34, $cd, $33, $cd
	.byte $ff, $12
	.word @song2ref257
	.byte $ff, $0f
	.word @song2ref293
	.byte $2c, $f7, $f5, $00, $cd, $f7, $f7, $cf, $fd
	.word @song2ch1loop
@song2ch2:
@song2ch2loop:
@song2ref327:
	.byte $80, $27, $a1, $00, $81, $27, $a1, $00, $81, $8c, $29, $00, $8f, $2e, $00, $8f, $80, $27, $8f, $00, $27, $8d, $00, $81
	.byte $8c, $29, $00, $8f, $2c, $00, $8f, $80, $27, $8f, $00, $8c, $2a, $00, $8f, $80, $27, $a1, $00, $81, $8c, $29, $00, $8f
	.byte $2f, $00, $8f
	.byte $ff, $2b
	.word @song2ref327
	.byte $ff, $2b
	.word @song2ref327
	.byte $ff, $2b
	.word @song2ref327
	.byte $ff, $2b
	.word @song2ref327
	.byte $ff, $2b
	.word @song2ref327
	.byte $ff, $2b
	.word @song2ref327
	.byte $ff, $2b
	.word @song2ref327
@song2ref399:
	.byte $80, $2c, $a1, $00, $81, $2c, $a1, $00, $81, $8c, $29, $00, $8f, $2e, $00, $8f, $80, $2c, $8f, $00, $2c, $8d, $00, $81
	.byte $8c, $29, $00, $8f, $2c, $00, $8f, $80, $2c, $8f, $00, $8c, $2a, $00, $8f, $80, $2c, $a1, $00, $81, $8c, $29, $00, $8f
	.byte $2f, $00, $8f
	.byte $ff, $2b
	.word @song2ref399
	.byte $ff, $2b
	.word @song2ref399
	.byte $ff, $2b
	.word @song2ref399
	.byte $ff, $2b
	.word @song2ref327
	.byte $ff, $2b
	.word @song2ref327
	.byte $ff, $2b
	.word @song2ref327
	.byte $ff, $2b
	.word @song2ref327
	.byte $fd
	.word @song2ch2loop
@song2ch3:
@song2ch3loop:
@song2ref475:
	.byte $8c, $4e, $91, $41, $91, $8a, $46, $91, $8c, $44, $91, $84, $41, $91, $8a, $46, $91, $84, $41, $91, $8a, $47, $91, $8c
	.byte $41, $91, $84, $44, $91, $41, $91, $42, $91, $41, $91, $46, $91, $41, $91, $47, $91
	.byte $ff, $20
	.word @song2ref475
	.byte $ff, $20
	.word @song2ref475
	.byte $ff, $20
	.word @song2ref475
	.byte $ff, $20
	.word @song2ref475
	.byte $ff, $20
	.word @song2ref475
	.byte $ff, $20
	.word @song2ref475
	.byte $ff, $20
	.word @song2ref475
	.byte $ff, $20
	.word @song2ref475
	.byte $ff, $20
	.word @song2ref475
	.byte $ff, $20
	.word @song2ref475
	.byte $ff, $20
	.word @song2ref475
	.byte $ff, $20
	.word @song2ref475
	.byte $ff, $20
	.word @song2ref475
	.byte $ff, $20
	.word @song2ref475
	.byte $ff, $20
	.word @song2ref475
	.byte $fd
	.word @song2ch3loop
@song2ch4:
@song2ch4loop:
@song2ref565:
	.byte $25, $cd, $00, $f5, $25, $cd, $00, $a5, $25, $cd, $00, $f5, $25, $cd, $00, $a5
	.byte $ff, $10
	.word @song2ref565
	.byte $ff, $10
	.word @song2ref565
	.byte $ff, $10
	.word @song2ref565
	.byte $ff, $10
	.word @song2ref565
	.byte $ff, $10
	.word @song2ref565
	.byte $ff, $10
	.word @song2ref565
	.byte $ff, $10
	.word @song2ref565
	.byte $fd
	.word @song2ch4loop
@song3ch0:
	.byte $92
@song3ref2:
	.byte $33, $cd, $3a, $cd, $38, $a5, $31, $a5, $33, $cd, $6b, $36, $cd, $35, $a5, $31, $a5, $33, $cd, $2e, $cd, $6b, $2c, $a5
	.byte $30, $a5, $31, $a5, $35, $a5, $33, $cd, $2e, $cd, $6b, $2c, $a5, $30, $a5, $2e, $a5, $2c, $a5, $2e, $f7, $a5, $6b
	.byte $ff, $2b
	.word @song3ref2
	.byte $6b, $90
@song3ref54:
	.byte $3a, $f7, $f5, $3c, $cd, $6b, $39, $f7, $a5, $3a, $cd, $3c, $cd, $6b, $39, $cd, $00, $3a, $cb, $3f, $cd, $41, $cd, $6b
	.byte $3d, $f7, $f7, $cd, $6b
	.byte $ff, $0e
	.word @song3ref54
	.byte $3a, $cd, $41, $cd, $3e, $cd, $6b, $3f, $f7, $f7, $cd, $6b, $f9, $cd, $00, $f7, $f5, $6b, $f7, $f7, $cf
@song3ch0loop:
	.byte $00, $fd
	.word @song3ch0loop
@song3ch1:
	.byte $92
@song3ref113:
	.byte $2e, $f7, $f7, $cd, $2e, $f7, $f7, $cd, $2e, $f7, $f7, $cd
	.byte $ff, $0c
	.word @song3ref113
	.byte $ff, $0c
	.word @song3ref113
	.byte $ff, $0c
	.word @song3ref113
	.byte $ff, $0c
	.word @song3ref113
	.byte $2e, $f7, $f7, $cd, $00, $f7, $f7, $cd, $f7, $f7, $cf
@song3ch1loop:
	.byte $00, $fd
	.word @song3ch1loop
@song3ch2:
	.byte $80
@song3ref154:
	.byte $27, $f7, $f7, $cd, $27, $f7, $f7, $cd, $27, $f7, $f7, $cd
	.byte $ff, $0c
	.word @song3ref154
	.byte $ff, $0c
	.word @song3ref154
	.byte $ff, $0c
	.word @song3ref154
@song3ref175:
	.byte $3c, $27, $89, $3d, $27, $87, $3e, $27, $89, $3f, $27, $89, $3e, $27, $87, $3d, $27, $89
	.byte $ff, $12
	.word @song3ref175
	.byte $ff, $12
	.word @song3ref175
	.byte $ff, $12
	.word @song3ref175
	.byte $ff, $12
	.word @song3ref175
	.byte $ff, $12
	.word @song3ref175
	.byte $ff, $12
	.word @song3ref175
	.byte $ff, $12
	.word @song3ref175
	.byte $ff, $12
	.word @song3ref175
	.byte $ff, $12
	.word @song3ref175
	.byte $ff, $12
	.word @song3ref175
	.byte $ff, $12
	.word @song3ref175
	.byte $ff, $12
	.word @song3ref175
	.byte $ff, $12
	.word @song3ref175
	.byte $ff, $12
	.word @song3ref175
	.byte $ff, $12
	.word @song3ref175
	.byte $00, $f7, $f7, $cd, $f7, $f7, $cf
@song3ch2loop:
	.byte $00, $fd
	.word @song3ch2loop
@song3ch3:
@song3ref250:
	.byte $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $a7, $8e
@song3ref262:
	.byte $30, $f5, $00, $a5, $f7, $a7, $30, $f5, $00, $a5, $f7, $a7
	.byte $ff, $0c
	.word @song3ref262
	.byte $30, $f5, $00, $a5, $88
@song3ref282:
	.byte $2e, $a5, $00, $a5, $2e, $a5, $20, $a5, $8e, $30, $f5, $88, $2e, $a5
	.byte $ff, $0c
	.word @song3ref282
	.byte $ff, $0c
	.word @song3ref282
	.byte $ff, $0c
	.word @song3ref282
	.byte $ff, $0c
	.word @song3ref282
	.byte $ff, $0c
	.word @song3ref282
	.byte $ff, $0c
	.word @song3ref282
	.byte $ff, $0c
	.word @song3ref282
	.byte $00, $f7, $f7, $cd, $f7, $f7, $cf
@song3ch3loop:
	.byte $00, $fd
	.word @song3ch3loop
@song3ch4:
	.byte $ff, $0a
	.word @song3ref250
	.byte $f7, $cf
@song3ref334:
	.byte $25, $f7, $a5, $25, $f7, $a5, $25, $f7, $a5, $25, $f7, $a5
	.byte $ff, $0c
	.word @song3ref334
@song3ref349:
	.byte $25, $91, $25, $a5, $25, $a5, $25, $91, $25, $f5, $27, $cd
	.byte $ff, $0c
	.word @song3ref349
	.byte $ff, $0c
	.word @song3ref349
	.byte $ff, $0c
	.word @song3ref349
	.byte $ff, $0c
	.word @song3ref349
	.byte $ff, $0c
	.word @song3ref349
	.byte $ff, $0c
	.word @song3ref349
	.byte $ff, $0c
	.word @song3ref349
	.byte $ff, $0a
	.word @song3ref349
	.byte $00, $cd
	.byte $ff, $0a
	.word @song3ref349
	.byte $00, $cd
@song3ch4loop:
	.byte $00, $fd
	.word @song3ch4loop
@song4ch0:
@song4ref1:
	.byte $82, $1d, $85, $00, $95, $24, $85, $00, $91, $8a, $1d, $81, $00, $97
@song4ref15:
	.byte $1d, $24, $81, $82, $24, $87, $00, $91, $8a, $24, $82, $1d, $85, $00, $91, $8a, $24, $81, $82, $24, $87, $00, $8d, $8a
	.byte $24, $1d, $81, $00, $9b, $1d, $00, $9d, $6b
	.byte $ff, $26
	.word @song4ref1
@song4ch0loop:
	.byte $6a, .lobyte(@tempo_env_8_mid), .hibyte(@tempo_env_8_mid)
	.byte $ff, $26
	.word @song4ref1
	.byte $6b
	.byte $ff, $26
	.word @song4ref1
	.byte $6b
	.byte $ff, $26
	.word @song4ref1
	.byte $6b
	.byte $ff, $26
	.word @song4ref1
	.byte $6b
	.byte $ff, $26
	.word @song4ref1
	.byte $6b
	.byte $ff, $26
	.word @song4ref1
	.byte $6b
	.byte $ff, $26
	.word @song4ref1
	.byte $6b
	.byte $ff, $26
	.word @song4ref1
	.byte $6b
	.byte $ff, $26
	.word @song4ref1
	.byte $6b
	.byte $ff, $26
	.word @song4ref1
@song4ref94:
	.byte $6b, $82, $19, $85, $00, $95, $20, $85, $00, $91, $8a, $19, $81, $00, $97, $19, $20, $81, $82, $20, $87, $00, $91, $8a
	.byte $20, $82, $19, $85, $00, $91, $8a, $20, $81, $82, $20, $87, $00, $8d, $8a, $20, $19, $81, $00, $9b, $19, $00, $9d, $6b
	.byte $82, $1b, $85, $00, $95, $22, $85, $00, $91, $8a, $1b, $81, $00, $97, $1b, $22, $81, $82, $22, $87, $00, $91, $8a, $22
	.byte $82, $1b, $85, $00, $91, $8a, $22, $81, $82, $22, $87, $00, $8d, $8a, $22, $1b, $81, $00, $9b, $1b, $00, $9d, $6b
	.byte $ff, $26
	.word @song4ref1
	.byte $6b
	.byte $ff, $26
	.word @song4ref1
	.byte $ff, $4c
	.word @song4ref94
	.byte $6b
	.byte $ff, $26
	.word @song4ref1
	.byte $6b
	.byte $ff, $26
	.word @song4ref1
@song4ref207:
	.byte $6b, $82, $16, $8d, $00, $9d, $8a, $16, $81, $00, $89, $82, $14, $8d, $00, $8b, $8a, $16, $00, $8d, $14, $81, $00, $89
	.byte $82, $19, $8d, $00, $8d, $8a, $14, $00, $8b, $19, $81, $00, $89, $82, $18, $8d, $00, $8d, $8a, $19, $00, $8b, $18, $81
	.byte $00, $89, $6b, $f7, $f7, $8f
	.byte $ff, $1e
	.word @song4ref207
@song4ref264:
	.byte $82, $1b, $8d, $00, $8d, $8a, $19, $00, $8b, $1b, $81, $00, $89, $6b, $8e, $22, $bd, $20, $bd, $25, $bd, $27, $bd
	.byte $ff, $2c
	.word @song4ref207
	.byte $ff, $1e
	.word @song4ref207
	.byte $ff, $13
	.word @song4ref264
	.byte $6b, $82, $22, $8d, $90, $22, $ad, $82, $20, $8d, $90, $20, $ad, $82, $25, $8d, $90, $25, $ad, $82, $24, $8d, $90, $24
	.byte $ad, $6b, $82, $29, $8d, $90, $29, $ad, $82, $2b, $8d, $90, $2b, $ad, $82, $2c, $8d, $90, $2c, $ad, $82, $2e, $8d, $90
	.byte $2e, $ad, $6b, $82, $30, $85, $90, $30, $95, $82, $24, $85, $90, $30, $a5, $f9, $87, $8a
	.byte $ff, $1a
	.word @song4ref15
	.byte $6b
	.byte $ff, $26
	.word @song4ref1
	.byte $fd
	.word @song4ch0loop
@song4ch1:
	.byte $f7, $f7, $8f, $f7, $f7, $8f
@song4ch1loop:
	.byte $f7, $f7, $8f
@song4ref382:
	.byte $f7, $f7, $8f, $84, $3f, $9d, $42, $99, $8a, $3f, $81, $84, $3d, $97, $8a, $3f, $42, $81, $84, $3f, $97, $8a, $42, $3d
	.byte $81, $84, $3c, $99, $8a, $3f, $81, $3d, $00, $97, $3c, $81, $3f, $00, $9b, $3c, $00, $9b, $f7, $e7, $84, $36, $9d, $35
	.byte $99, $8a, $36, $81, $84, $3c, $97, $8a, $36, $35, $81, $00, $97, $35, $3c, $81, $00, $97, $3c, $00, $f7, $89
	.byte $ff, $3a
	.word @song4ref382
@song4ref455:
	.byte $f7, $f7, $8f, $84, $41, $9d, $44, $99, $8a, $41, $81, $84, $41, $97, $8a, $41, $44, $81, $84, $3f, $97, $8a, $44, $41
	.byte $81, $84, $41, $97, $8a, $41, $3f, $81, $00, $97, $3f, $41, $81, $00, $9b, $41, $00, $9d, $84, $43, $9d, $46, $99, $8a
	.byte $43, $81, $84, $43, $97, $8a, $43, $46, $81, $84, $41, $97, $8a, $46, $43, $81, $84, $43, $97, $8a, $43, $41, $81, $00
	.byte $97, $41, $43, $81, $00, $9b, $43, $00, $99, $84, $43, $81, $44, $9d, $00, $99, $8a, $44, $81, $00, $9b, $44, $84, $43
	.byte $9d, $41, $99, $8a, $43, $81, $00, $99, $41, $81, $43, $00, $9b, $41, $00, $9b
	.byte $ff, $4c
	.word @song4ref455
	.byte $84, $46, $9d, $48, $99, $8a, $46, $81, $00, $99, $48, $81, $46, $00, $9b, $48, $00, $9b, $f7, $f7, $8f
@song4ref591:
	.byte $84, $3a, $9d, $00, $99, $8a, $3a, $81, $84, $38, $9b, $8a, $3a, $00, $99, $38, $81, $84, $3d, $9b, $8a, $38, $00, $99
	.byte $3d, $81, $84, $3c, $9b, $8a, $3d, $00, $99, $3c
@song4ref625:
	.byte $81, $90, $22, $8d, $00, $9d, $22, $81, $00, $89, $20, $8d, $00, $8b, $22, $00, $8d, $20, $81, $00, $89, $25, $8d, $00
	.byte $8d, $20, $00, $8b, $25, $81, $00, $89, $24, $8d, $00, $8d, $25, $00, $8b, $24, $81, $00, $89
	.byte $ff, $14
	.word @song4ref591
	.byte $84, $3f, $9b, $8a, $3d, $00, $99, $3f
	.byte $ff, $2a
	.word @song4ref625
	.byte $ff, $44
	.word @song4ref591
	.byte $ff, $14
	.word @song4ref591
	.byte $84, $3f, $9b, $8a, $3d, $00, $99, $3f
	.byte $ff, $2a
	.word @song4ref625
	.byte $ff, $1b
	.word @song4ref591
	.byte $84, $41, $9d, $8a, $3c, $00, $97, $41, $81, $84, $43, $9d, $8a, $41, $00, $97, $43, $81, $84, $44, $9d, $8a, $43, $00
	.byte $97, $44, $81, $84, $46, $9d, $8a, $44, $00, $97, $46, $81, $84, $48, $9d, $8a, $46, $00, $97, $48, $81, $00, $9d, $48
	.byte $00, $f7, $a3, $f7, $f7, $8f, $fd
	.word @song4ch1loop
@song4ch2:
@song4ref759:
	.byte $80
@song4ref760:
	.byte $1d, $81, $00, $99, $24, $81, $00, $b9
@song4ref768:
	.byte $24, $81, $00, $99, $1d, $81, $00, $99, $24, $81, $00, $99, $0c, $00, $9b, $0c, $00, $9b
	.byte $ff, $1a
	.word @song4ref760
@song4ch2loop:
	.byte $ff, $1a
	.word @song4ref759
	.byte $ff, $1a
	.word @song4ref760
	.byte $ff, $1a
	.word @song4ref760
	.byte $ff, $13
	.word @song4ref760
@song4ref802:
	.byte $b9, $1e, $9d, $1d, $9d, $24, $95, $00, $a5
	.byte $ff, $0b
	.word @song4ref768
	.byte $d9
	.byte $ff, $1a
	.word @song4ref760
	.byte $ff, $1a
	.word @song4ref760
	.byte $ff, $13
	.word @song4ref760
	.byte $ff, $09
	.word @song4ref802
	.byte $ff, $0b
	.word @song4ref768
	.byte $d9
	.byte $ff, $1a
	.word @song4ref760
	.byte $25, $81, $00, $99, $2c, $81, $00, $b9, $2c, $81, $00, $99, $25, $81, $00, $99, $2c, $81, $00, $99, $0d, $00, $9b, $0d
	.byte $00, $9b, $27, $81, $00, $99, $2e, $81, $00, $b9, $2e, $81, $00, $99, $27, $81, $00, $99, $2e, $81, $00, $99, $0f, $00
	.byte $9b, $0f, $00, $9b
	.byte $ff, $1a
	.word @song4ref760
	.byte $ff, $1a
	.word @song4ref760
@song4ref892:
	.byte $16, $83, $00, $95, $16, $00, $9d, $14, $83, $00, $95, $14, $00, $9d, $19, $83, $00, $95, $19, $00, $9d, $18, $83, $00
	.byte $95, $18, $00, $9d, $1d, $81, $00, $97, $1d, $00, $9d, $1f, $81, $00, $97, $1f, $00, $9d, $20, $81, $00, $97, $20, $00
	.byte $9d, $22, $81, $00, $97, $22, $00, $9d
	.byte $ff, $1a
	.word @song4ref760
	.byte $ff, $1a
	.word @song4ref760
	.byte $ff, $1c
	.word @song4ref892
@song4ref957:
	.byte $11, $85, $00, $95, $11, $85, $00, $b5, $11, $85, $00, $95
	.byte $ff, $09
	.word @song4ref957
	.byte $00, $9b
	.byte $ff, $15
	.word @song4ref892
	.byte $1b, $83, $00, $95, $1b, $00, $9d
	.byte $ff, $0c
	.word @song4ref957
	.byte $ff, $09
	.word @song4ref957
	.byte $00, $9b
	.byte $ff, $1c
	.word @song4ref892
	.byte $ff, $0c
	.word @song4ref957
	.byte $ff, $09
	.word @song4ref957
	.byte $00, $9b
	.byte $ff, $15
	.word @song4ref892
	.byte $1b, $83, $00, $95, $1b, $00, $9d
	.byte $ff, $0c
	.word @song4ref957
	.byte $ff, $09
	.word @song4ref957
	.byte $00, $9b
	.byte $ff, $38
	.word @song4ref892
	.byte $ff, $1a
	.word @song4ref760
	.byte $ff, $1a
	.word @song4ref760
	.byte $fd
	.word @song4ch2loop
@song4ch3:
@song4ref1033:
	.byte $86, $0f, $99, $00, $81, $8a, $10, $89, $00, $b1, $8c, $1f, $87, $00, $93, $86, $0f, $99, $00, $81, $8c, $1f, $85, $8a
	.byte $1d, $81, $00, $91, $1d, $00, $bb
	.byte $ff, $19
	.word @song4ref1033
@song4ch3loop:
	.byte $ff, $19
	.word @song4ref1033
	.byte $ff, $18
	.word @song4ref1033
@song4ref1074:
	.byte $9b, $8c, $0d, $83, $00, $87, $0e, $83, $00, $87
	.byte $ff, $19
	.word @song4ref1033
	.byte $ff, $19
	.word @song4ref1033
	.byte $ff, $19
	.word @song4ref1033
	.byte $ff, $18
	.word @song4ref1033
	.byte $ff, $09
	.word @song4ref1074
	.byte $ff, $19
	.word @song4ref1033
	.byte $ff, $19
	.word @song4ref1033
	.byte $ff, $19
	.word @song4ref1033
	.byte $ff, $18
	.word @song4ref1033
	.byte $ff, $09
	.word @song4ref1074
	.byte $ff, $19
	.word @song4ref1033
	.byte $ff, $19
	.word @song4ref1033
	.byte $ff, $19
	.word @song4ref1033
	.byte $ff, $18
	.word @song4ref1033
	.byte $ff, $09
	.word @song4ref1074
	.byte $ff, $19
	.word @song4ref1033
	.byte $ff, $19
	.word @song4ref1033
	.byte $ff, $19
	.word @song4ref1033
	.byte $ff, $18
	.word @song4ref1033
	.byte $ff, $09
	.word @song4ref1074
@song4ref1144:
	.byte $1d, $89, $00, $a1, $1d, $00, $87, $1d, $00, $1d, $87, $00, $93, $1d, $00, $8b, $1d, $00, $8b, $82, $14, $93, $00, $87
	.byte $8c, $1d, $00, $89, $1d, $00, $8d, $1d, $8d, $00, $8d, $1d, $00, $8b, $1d, $00, $8b
	.byte $ff, $27
	.word @song4ref1144
	.byte $ff, $27
	.word @song4ref1144
	.byte $ff, $27
	.word @song4ref1144
	.byte $ff, $27
	.word @song4ref1144
	.byte $ff, $27
	.word @song4ref1144
	.byte $ff, $27
	.word @song4ref1144
	.byte $ff, $27
	.word @song4ref1144
	.byte $ff, $27
	.word @song4ref1144
	.byte $ff, $1d
	.word @song4ref1144
	.byte $82, $14, $93, $00, $87, $8c, $12, $81, $00, $89, $10, $81, $00, $89
	.byte $ff, $19
	.word @song4ref1033
	.byte $ff, $19
	.word @song4ref1033
	.byte $fd
	.word @song4ch3loop
@song4ch4:
	.byte $f7, $f7, $8f, $f7, $f7, $8f
@song4ch4loop:
@song4ref1242:
	.byte $f7, $f7, $8f, $f7, $f7, $8f, $f7, $f7, $8f
	.byte $ff, $09
	.word @song4ref1242
	.byte $ff, $09
	.word @song4ref1242
	.byte $ff, $09
	.word @song4ref1242
	.byte $ff, $09
	.word @song4ref1242
	.byte $ff, $09
	.word @song4ref1242
	.byte $ff, $09
	.word @song4ref1242
	.byte $ff, $09
	.word @song4ref1242
	.byte $ff, $09
	.word @song4ref1242
	.byte $ff, $09
	.word @song4ref1242
	.byte $fd
	.word @song4ch4loop
@song5ch0:
@song5ch0loop:
	.byte $6a, .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid), $84, $46, $a3, $8a, $44, $84, $45, $a3, $8a, $43
@song5ref15:
	.byte $84, $3f, $a3, $8a, $46, $84, $46, $a3, $8a, $45, $84, $45, $a3, $8a, $3f
	.byte $ff, $09
	.word @song5ref15
	.byte $6b, $84, $44, $a3, $8a, $46, $84, $43, $a3, $8a, $45
@song5ref44:
	.byte $84, $3d, $a3, $8a, $44, $84, $44, $a3, $8a, $43, $84, $43, $a3, $8a, $3d
	.byte $ff, $09
	.word @song5ref44
	.byte $fd
	.word @song5ch0loop
@song5ch1:
@song5ch1loop:
	.byte $93, $8a
@song5ref68:
	.byte $46, $85, $00, $9d, $45, $85, $00, $9d, $3f, $85, $00, $9d
	.byte $ff, $0c
	.word @song5ref68
	.byte $46, $85, $00, $9d, $45, $85, $00, $89, $93, $3f, $85, $00, $9d
@song5ref96:
	.byte $43, $87, $00, $9b, $3d, $87, $00, $9b, $44, $87, $00, $9b
	.byte $ff, $0c
	.word @song5ref96
	.byte $43, $87, $00, $87, $fd
	.word @song5ch1loop
@song5ch2:
@song5ch2loop:
	.byte $f7, $f7, $cf, $f7, $f7, $cf, $fd
	.word @song5ch2loop
@song5ch3:
@song5ch3loop:
	.byte $f7, $f7, $cf, $f7, $f7, $cf, $fd
	.word @song5ch3loop
@song5ch4:
@song5ch4loop:
	.byte $f7, $f7, $cf, $f7, $f7, $cf, $fd
	.word @song5ch4loop
@song6ch0:
	.byte $f7, $a7
@song6ch0loop:
	.byte $6a, .lobyte(@tempo_env_10_mid), .hibyte(@tempo_env_10_mid), $f7, $f7, $cf, $6b, $f7, $f7, $cf, $6b, $f7, $f7, $cf
	.byte $6b, $f7, $f7, $cf, $6b, $90
@song6ref24:
	.byte $0f, $f7, $a5, $12, $f7, $a5, $6b, $0e, $f7, $a5, $f9, $cd, $00, $cd, $6b, $0f, $f7, $a5, $12, $f7, $a5, $6b, $17, $91
	.byte $14, $91, $16, $f5, $f9, $cd, $00, $cd, $6b
	.byte $ff, $1d
	.word @song6ref24
	.byte $6b, $8a
@song6ref62:
	.byte $2e, $87, $00, $87, $2e, $87, $00, $85, $2e, $2e, $87, $00, $85, $2e, $2e, $87, $00, $93, $2e, $81, $00, $81, $2e, $87
	.byte $00, $87, $2e, $00, $8b, $2e, $81, $2e, $89, $00, $83, $2e, $27, $89, $00, $81, $2e, $81, $00, $8b, $27, $81, $2e, $27
	.byte $89, $00, $85, $27, $00, $8b, $27, $81, $00, $8f, $27, $00, $91, $27, $00, $a3, $6b
	.byte $ff, $40
	.word @song6ref62
@song6ref130:
	.byte $6b, $2d, $87, $00, $87, $2d, $87, $00, $85, $2d, $2d, $87, $00, $85, $2d, $2d, $87, $00, $93, $2d, $81, $00, $81, $2d
	.byte $87, $00, $87, $2d, $00, $8b, $2d, $81, $2d, $89, $00, $83, $2d, $29, $89, $00, $81, $2d, $81, $00, $8b, $29, $81, $2d
	.byte $29, $89, $00, $85, $29, $00, $8b, $29, $81, $00, $8f, $29, $00, $91, $29, $00, $a3
	.byte $ff, $40
	.word @song6ref130
	.byte $6b
	.byte $ff, $40
	.word @song6ref62
	.byte $6b
	.byte $ff, $40
	.word @song6ref62
	.byte $ff, $40
	.word @song6ref130
	.byte $ff, $40
	.word @song6ref130
	.byte $fd
	.word @song6ch0loop
@song6ch1:
	.byte $f7, $a7
@song6ch1loop:
@song6ref218:
	.byte $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf
	.byte $ff, $0c
	.word @song6ref218
	.byte $82, $1e, $f7, $a5, $21, $f7, $a5, $1d, $cd, $00, $f7, $a5, $8e, $15, $cd, $82, $1e, $f7, $a5, $21, $f7, $a5, $26, $91
	.byte $23, $91, $25, $f5, $00, $f7, $a5, $8a
@song6ref265:
	.byte $46, $f7, $a5, $42, $f7, $a5, $3e, $f7, $a5, $3f, $f7, $a5, $42, $91, $3f, $91, $41, $f7, $f7, $91, $f9, $91, $00, $f7
	.byte $f7, $cd
	.byte $ff, $1a
	.word @song6ref265
	.byte $fd
	.word @song6ch1loop
@song6ch2:
	.byte $f7, $a7
@song6ch2loop:
	.byte $80
@song6ref301:
	.byte $2a, $83, $00, $8b, $2c, $00, $8f, $2e, $00, $8f, $25, $00, $a3, $1b, $85, $00, $9d, $1b, $85, $00, $f7, $b1
	.byte $ff, $16
	.word @song6ref301
	.byte $ff, $16
	.word @song6ref301
	.byte $ff, $16
	.word @song6ref301
	.byte $ff, $16
	.word @song6ref301
	.byte $ff, $16
	.word @song6ref301
	.byte $ff, $16
	.word @song6ref301
	.byte $ff, $16
	.word @song6ref301
	.byte $ff, $16
	.word @song6ref301
	.byte $ff, $16
	.word @song6ref301
	.byte $ff, $16
	.word @song6ref301
	.byte $ff, $16
	.word @song6ref301
@song6ref356:
	.byte $2a, $83, $00, $8b, $2c, $00, $8f, $2e, $00, $8f, $26, $00, $a3, $22, $81, $00, $8d, $22, $00, $8f, $1a, $00, $8f, $1b
	.byte $85, $00, $9d, $1b, $85, $00, $ed
	.byte $ff, $1f
	.word @song6ref356
@song6ref390:
	.byte $2d, $83, $00, $8b, $2e, $00, $8f, $30, $00, $8f, $27, $00, $a3, $24, $81, $00, $8d, $24, $00, $8f, $1c, $00, $8f, $1d
	.byte $85, $00, $9d, $1d, $85, $00, $ed
	.byte $ff, $1f
	.word @song6ref390
	.byte $ff, $1f
	.word @song6ref356
	.byte $ff, $1f
	.word @song6ref356
	.byte $ff, $1f
	.word @song6ref390
	.byte $ff, $1f
	.word @song6ref390
	.byte $fd
	.word @song6ch2loop
@song6ch3:
	.byte $db, $8e, $30, $c1
@song6ch3loop:
@song6ref444:
	.byte $88, $2e, $8a, $23, $85, $00, $87, $88, $2e, $8a, $2f, $85, $00, $87, $88, $2e, $80, $30, $87, $00, $85, $88, $2e, $80
	.byte $2f, $83, $00, $9d, $88, $2e, $80, $2f, $8f, $00, $91, $88, $2e, $8a, $23, $89, $00, $83, $80, $30, $89, $8e, $30, $99
	.byte $80, $30, $89, $8e, $30, $99, $00, $89, $30, $c1
	.byte $ff, $2a
	.word @song6ref444
	.byte $ff, $2a
	.word @song6ref444
	.byte $ff, $2a
	.word @song6ref444
	.byte $ff, $2a
	.word @song6ref444
	.byte $ff, $2a
	.word @song6ref444
	.byte $ff, $2a
	.word @song6ref444
	.byte $ff, $2a
	.word @song6ref444
	.byte $ff, $2a
	.word @song6ref444
	.byte $ff, $2a
	.word @song6ref444
	.byte $ff, $2a
	.word @song6ref444
	.byte $ff, $2a
	.word @song6ref444
	.byte $ff, $2a
	.word @song6ref444
	.byte $ff, $2a
	.word @song6ref444
	.byte $ff, $2a
	.word @song6ref444
	.byte $ff, $2a
	.word @song6ref444
	.byte $ff, $2a
	.word @song6ref444
	.byte $ff, $2a
	.word @song6ref444
	.byte $ff, $2a
	.word @song6ref444
	.byte $ff, $2a
	.word @song6ref444
	.byte $fd
	.word @song6ch3loop
@song6ch4:
	.byte $f7, $a7
@song6ch4loop:
@song6ref565:
	.byte $25, $f7, $a5, $00, $f7, $a5, $25, $f7, $a5, $00, $f7, $a5
	.byte $ff, $0c
	.word @song6ref565
	.byte $ff, $0c
	.word @song6ref565
	.byte $ff, $0c
	.word @song6ref565
	.byte $ff, $0c
	.word @song6ref565
	.byte $ff, $0c
	.word @song6ref565
	.byte $ff, $0c
	.word @song6ref218
	.byte $ff, $0c
	.word @song6ref218
	.byte $fd
	.word @song6ch4loop
