; This file for the FamiTone2 library and was generated by FamiStudio

.if FAMISTUDIO_CFG_C_BINDINGS
.export _music_data_the_trial_of_kharzoid_ost=music_data_the_trial_of_kharzoid_ost
.endif

music_data_the_trial_of_kharzoid_ost:
	.byte 2
	.word @instruments
	.word @samples-111
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256

.export music_data_the_trial_of_kharzoid_ost
.global FAMISTUDIO_DPCM_PTR

@instruments:
	.byte $b0 ;instrument 00 (Bass)
	.word @env5, @env0, @env0
	.byte $00
	.byte $30 ;instrument 01 (Metal Percussion)
	.word @env4, @env0, @env0
	.byte $00
	.byte $b0 ;instrument 02 (Pluck)
	.word @env2, @env0, @env0
	.byte $00
	.byte $30 ;instrument 03 (Reverse Cymbal)
	.word @env7, @env0, @env0
	.byte $00
	.byte $b0 ;instrument 04 (Tri-Flute)
	.word @env1, @env0, @env8
	.byte $00
	.byte $70 ;instrument 05 (Violin)
	.word @env6, @env0, @env3
	.byte $00

@samples:
	.byte $00+.lobyte(FT_DPCM_PTR),$db,$0f	;37 (sample_tom)
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;38 
	.byte $37+.lobyte(FT_DPCM_PTR),$de,$0f	;39 (sfx_voice_D)
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;40 
	.byte $6f+.lobyte(FT_DPCM_PTR),$de,$0f	;41 (sfx_voice_Em)

@env0:
	.byte $c0,$7f,$00,$00
@env1:
	.byte $c3,$7f,$00,$00
@env2:
	.byte $c5,$7f,$00,$00
@env3:
	.byte $c0,$0d,$c1,$c1,$c0,$03,$bf,$bf,$c0,$03,$c1,$c1,$c0,$03,$c1,$c1,$c2,$c2,$c1,$c1,$c0,$03,$bf,$bf,$be,$be,$bf,$bf,$00,$0e
@env4:
	.byte $c8,$cf,$cd,$cc,$cc,$cb,$ca,$c9,$c8,$c8,$c7,$c6,$c6,$c5,$c4,$c3,$02,$c2,$c2,$c1,$0a,$c0,$00,$15
@env5:
	.byte $c7,$7f,$00,$00
@env6:
	.byte $c3,$05,$c4,$05,$c5,$02,$c6,$c6,$c7,$c7,$c8,$c8,$c9,$c9,$ca,$04,$c9,$c8,$c7,$c6,$c6,$c6,$00,$13
@env7:
	.byte $c0,$c0,$c1,$0b,$c2,$02,$c3,$04,$c4,$04,$c5,$03,$c6,$c6,$c7,$02,$c8,$c9,$ca,$cb,$cb,$cc,$ce,$ce,$cf,$c7,$c7,$c6,$03,$c5,$c5,$c4,$c4,$c3,$03,$c2,$c2,$c1,$c1,$c0,$00,$27
@env8:
	.byte $c0,$07,$c1,$c1,$c0,$03,$bf,$bf,$c0,$03,$c1,$03,$c0,$03,$bf,$02,$bf,$00,$08
@song0ch0:
	.byte $fb, $01
@song0ch0loop:
	.byte $84
@song0ref5:
	.byte $07, $00, $a1, $0d, $00, $a1, $15, $00, $a1, $1f, $00, $a1, $2d, $00, $f9, $9f
	.byte $ff, $10
	.word @song0ref5
@song0ref24:
	.byte $0b, $00, $a1, $11, $00, $a1, $19, $00, $a1, $23, $00, $a1, $29, $00, $f9, $9f
	.byte $ff, $10
	.word @song0ref24
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $10
	.word @song0ref5
	.byte $ff, $10
	.word @song0ref24
	.byte $ff, $0e
	.word @song0ref24
	.byte $c9, $88
@song0ref57:
	.byte $52
@song0ref58:
	.byte $cd, $84, $07, $88, $5c, $a1, $84, $0d, $88, $5c, $a1, $84, $15, $88, $5c, $a1, $84, $1f, $88, $5c, $a1, $84, $2d, $88
	.byte $5c, $c9, $58
	.byte $ff, $10
	.word @song0ref58
	.byte $60
@song0ref89:
	.byte $cd, $84, $0b, $88, $58, $a1, $84, $11, $88, $58, $a1, $84, $19, $88, $58, $a1, $84, $23, $88, $58, $a1, $84, $29, $88
	.byte $58, $c9, $54
	.byte $ff, $10
	.word @song0ref89
	.byte $ff, $10
	.word @song0ref57
	.byte $cb, $60, $cb, $84, $07, $88, $62, $a1, $84, $0d, $88, $62, $a1, $84, $15, $88, $62, $a1, $84, $1f, $88, $62, $a1, $84
	.byte $2d, $88, $62, $c9, $6a, $cd, $84, $0b, $88, $66, $a1, $84, $11, $88, $66, $a1, $84, $19, $00, $88, $58, $9f, $84, $23
	.byte $00, $88, $58, $9f, $84, $29, $88, $58, $c9, $5c, $cd, $84, $0b, $88, $60, $a1, $84, $11, $88, $60, $a1, $84, $19, $88
	.byte $60, $a1, $84, $23, $88, $60, $a1, $84, $29, $88, $60, $c9, $6a, $cd
@song0ref208:
	.byte $74, $f9, $f9, $c5, $00, $81, $74, $f9, $f9, $c5, $00, $81
	.byte $ff, $0c
	.word @song0ref208
	.byte $8a
@song0ref224:
	.byte $3e, $87, $40, $87, $42, $87, $44, $87, $46, $87, $44, $87, $42, $87, $40, $87
	.byte $ff, $10
	.word @song0ref224
	.byte $ff, $10
	.word @song0ref224
	.byte $ff, $10
	.word @song0ref224
	.byte $ff, $10
	.word @song0ref224
	.byte $ff, $10
	.word @song0ref224
	.byte $ff, $10
	.word @song0ref224
	.byte $ff, $10
	.word @song0ref224
	.byte $ff, $10
	.word @song0ref224
	.byte $ff, $10
	.word @song0ref224
	.byte $ff, $10
	.word @song0ref224
	.byte $ff, $10
	.word @song0ref224
	.byte $ff, $10
	.word @song0ref224
	.byte $ff, $10
	.word @song0ref224
	.byte $ff, $10
	.word @song0ref224
	.byte $ff, $10
	.word @song0ref224
	.byte $00, $f9, $f9, $c9, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $fd
	.word @song0ch0loop
@song0ch1:
@song0ch1loop:
@song0ref302:
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $8a
@song0ref315:
	.byte $1e, $f9, $f1, $01, $22, $cb, $24, $f9, $f5, $28, $c9, $00, $85, $22, $f9, $ef, $1e, $c9, $00, $22, $f9, $f3, $1a, $cd
	.byte $ff, $18
	.word @song0ref315
	.byte $ff, $18
	.word @song0ref315
	.byte $00, $f9, $f9, $c9, $88
@song0ref350:
	.byte $72, $f9, $f9, $c9, $70, $f9, $f9, $c9, $6e, $f9, $f9, $c5, $00, $81, $74, $f9, $f9, $c5, $00, $81
	.byte $ff, $0e
	.word @song0ref350
	.byte $ff, $0c
	.word @song0ref302
	.byte $fd
	.word @song0ch1loop
@song0ch2:
@song0ch2loop:
	.byte $80
@song0ref381:
	.byte $1e, $f9, $f9, $c9, $1e, $f9, $f9, $c9, $22, $f9, $f9, $c9, $22, $f9, $f9, $c9
	.byte $ff, $10
	.word @song0ref381
	.byte $ff, $10
	.word @song0ref381
	.byte $ff, $10
	.word @song0ref381
@song0ref406:
	.byte $1e, $f9, $f9, $c9, $1e, $f9, $f9, $c9, $1e, $f9, $f9, $c9
	.byte $ff, $0c
	.word @song0ref406
	.byte $ff, $0c
	.word @song0ref406
	.byte $ff, $0c
	.word @song0ref406
	.byte $fd
	.word @song0ch2loop
@song0ch3:
@song0ch3loop:
@song0ref431:
	.byte $82, $5e, $cd, $5c, $cd, $5e, $cd, $5c, $83, $86, $5c, $c7, $82, $5e, $cd, $5c, $cd, $5e, $cd, $5c, $83, $86, $5c, $c7
	.byte $ff, $14
	.word @song0ref431
	.byte $ff, $14
	.word @song0ref431
	.byte $ff, $14
	.word @song0ref431
	.byte $ff, $14
	.word @song0ref431
	.byte $ff, $14
	.word @song0ref431
	.byte $ff, $14
	.word @song0ref431
	.byte $ff, $14
	.word @song0ref431
@song0ref476:
	.byte $82, $56, $83, $86, $56, $c7, $82, $40, $85, $01, $86, $54, $97, $56, $5c, $a5, $56, $a5, $46, $cd, $5e, $a5
	.byte $ff, $12
	.word @song0ref476
	.byte $ff, $12
	.word @song0ref476
	.byte $ff, $12
	.word @song0ref476
	.byte $ff, $12
	.word @song0ref476
	.byte $ff, $12
	.word @song0ref476
	.byte $ff, $12
	.word @song0ref476
	.byte $ff, $12
	.word @song0ref476
@song0ref519:
	.byte $60, $a5, $88, $48, $91, $86, $62, $91, $88, $70, $91, $46, $91, $86, $6c, $b9, $88, $5c, $91, $86, $6c, $a5, $50, $91
	.byte $00, $a5, $72, $91
	.byte $ff, $16
	.word @song0ref519
	.byte $ff, $16
	.word @song0ref519
	.byte $ff, $16
	.word @song0ref519
	.byte $fd
	.word @song0ch3loop
@song0ch4:
@song0ch4loop:
@song0ref560:
	.byte $4a, $f9, $a3, $4e, $f3, $00, $4a, $a5, $4a, $f9, $a3, $4e, $f9, $a3, $4a, $f9, $a3, $52, $f5, $4a, $a5, $4a, $f9, $a3
	.byte $52, $f5, $4a, $a5
	.byte $ff, $1c
	.word @song0ref560
	.byte $ff, $1c
	.word @song0ref560
	.byte $ff, $1c
	.word @song0ref560
@song0ref597:
	.byte $4a, $91, $4a, $a5, $4a, $a5, $4a, $91, $4a, $f5, $4e, $cd
	.byte $ff, $0c
	.word @song0ref597
	.byte $ff, $0c
	.word @song0ref597
	.byte $ff, $0c
	.word @song0ref597
	.byte $ff, $0c
	.word @song0ref597
	.byte $ff, $0c
	.word @song0ref597
	.byte $ff, $0c
	.word @song0ref597
	.byte $ff, $0c
	.word @song0ref597
@song0ref630:
	.byte $4a, $f9, $a3, $00, $f5, $4a, $a5, $4a, $f9, $a3, $00, $f5, $4a, $a5
	.byte $ff, $0e
	.word @song0ref630
	.byte $fd
	.word @song0ch4loop
@song1ch0:
	.byte $fb, $01
@song1ch0loop:
@song1ref4:
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb
	.byte $f9, $f9, $cb, $f9, $f9, $cb
	.byte $ff, $1e
	.word @song1ref4
	.byte $ff, $1e
	.word @song1ref4
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $fd
	.word @song1ch0loop
@song1ch1:
@song1ch1loop:
	.byte $82
@song1ref51:
	.byte $1e, $9d, $20, $9d, $1e, $9d, $20, $9d, $1e, $9d, $24, $9d, $1e, $9d, $24, $9d, $1e, $9d, $28, $9d, $1e, $9d, $2a, $9d
	.byte $1e, $9d, $2a, $9d, $1e, $9d, $2c, $9d, $1e, $9d, $2c, $9d, $1e, $9d, $2e, $9d
	.byte $ff, $28
	.word @song1ref51
	.byte $ff, $28
	.word @song1ref51
	.byte $ff, $28
	.word @song1ref51
	.byte $00, $f9, $f9, $c9
	.byte $ff, $1e
	.word @song1ref4
	.byte $ff, $1e
	.word @song1ref4
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $fd
	.word @song1ch1loop
@song1ch2:
@song1ch2loop:
	.byte $80
@song1ref124:
	.byte $1e, $f5, $00, $85, $1e, $f5, $00, $85, $1e, $b5, $00, $85, $1e, $f5, $00, $85, $1e, $f5, $00, $85, $1e, $b5, $00, $85
	.byte $24, $f5, $00, $85, $24, $f5, $00, $85, $24, $b5, $00, $85, $24, $f5, $00, $85, $24, $f5, $00, $85, $24, $b5, $00, $85
	.byte $ff, $30
	.word @song1ref124
	.byte $ff, $1e
	.word @song1ref4
	.byte $ff, $1e
	.word @song1ref4
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $fd
	.word @song1ch2loop
@song1ch3:
@song1ch3loop:
	.byte $82
@song1ref198:
	.byte $4a, $9d, $88, $56, $9d, $4c, $9d, $86, $5a, $9d, $82, $4a, $9d, $88, $48, $9d, $82, $40, $9d, $50, $9d, $4a, $9d, $52
	.byte $9d, $4a, $9d, $88, $56, $9d, $4c, $9d, $86, $5a, $9d, $82, $4a, $9d, $88, $48, $9d, $82, $40, $9d, $50, $9d, $4a, $9d
	.byte $52, $9d
	.byte $ff, $28
	.word @song1ref198
	.byte $ff, $28
	.word @song1ref198
	.byte $ff, $28
	.word @song1ref198
	.byte $ff, $28
	.word @song1ref198
	.byte $00, $f9, $f9, $c9
	.byte $ff, $1e
	.word @song1ref4
	.byte $ff, $1e
	.word @song1ref4
	.byte $f9, $f9, $cb, $fd
	.word @song1ch3loop
@song1ch4:
@song1ch4loop:
@song1ref277:
	.byte $4a, $f9, $83, $4a, $f9, $83, $4a, $bd, $4a, $f9, $83, $4a, $f9, $83, $4a, $bd, $4a, $f9, $83, $4a, $f9, $83, $4a, $bd
	.byte $4a, $f9, $83, $4a, $f9, $83, $4a, $bd
	.byte $ff, $20
	.word @song1ref277
	.byte $00, $f9, $f9, $c9
	.byte $ff, $1e
	.word @song1ref4
	.byte $ff, $1e
	.word @song1ref4
	.byte $f9, $f9, $cb, $f9, $f9, $cb, $f9, $f9, $cb, $fd
	.word @song1ch4loop
