; This file is for the FamiStudio Sound Engine and was generated by FamiStudio


.if FAMISTUDIO_CFG_C_BINDINGS
.export _sounds=sounds
.endif

sounds:
	.word @ntsc
	.word @ntsc
@ntsc:
	.word @sfx_ntsc_fx_debug

@sfx_ntsc_fx_debug:
	.byte $82,$00,$81,$54,$80,$3f,$89,$f0,$14,$00

.export sounds
